::[Bat To Exe Converter]
::
::YAwzoRdxOk+EWAjk
::fBw5plQjdCmDJHSF5ks/aDxVQQG+taJ2j1LwbS0+u+C7q04SWqw2e4C7
::YAwzuBVtJxjWCl3EqQJgSA==
::ZR4luwNxJguZRRnk
::Yhs/ulQjdF+5
::cxAkpRVqdFKZSDk=
::cBs/ulQjdF+5
::ZR41oxFsdFKZSDk=
::eBoioBt6dFKZSDk=
::cRo6pxp7LAbNWATEpCI=
::egkzugNsPRvcWATEpCI=
::dAsiuh18IRvcCxnZtBJQ
::cRYluBh/LU+EWAnk
::YxY4rhs+aU+IeA==
::cxY6rQJ7JhzQF1fEqQJjZkoaHErSXA==
::ZQ05rAF9IBncCkqN+0xwdVsHAlXMbCXqZg==
::ZQ05rAF9IAHYFVzEqQJkAi9bQwiRXA==
::eg0/rx1wNQPfEVWB+kM9LVsJDGQ=
::fBEirQZwNQPfEVWB+kM9LVsJDFCoCGS1CqZ8
::cRolqwZ3JBvQF1fEqQJQ
::dhA7uBVwLU+EWGCN8EM/MhNVQju7PQs=
::YQ03rBFzNR3SWATElA==
::dhAmsQZ3MwfNWATElA==
::ZQ0/vhVqMQ3MEVWAtB9wSA==
::Zg8zqx1/OA3MEVWAtB9wSA==
::dhA7pRFwIByZRRnk
::Zh4grVQjdCmDJHSF5ks/aDxVQQG+aEGbCrAd/Ofp5vCGpkIPaLYVTIDU1qfAJfgWig==
::YB416Ek+ZG8=
::
::
::978f952a14a936cc963da21a135fa983
@echo off
color f0
setlocal enabledelayedexpansion
mode con cols=50 lines=15
cd "%~dp0"
pushd "%cd%"

set genmsg05=HTTPS://GITHUB.COM/YIDAOZHANYA/4JTOOLS
:lang
chcp 936>nul 2>nul||goto lang2
set msgtitle=SM4J - 世界随机器 v3.1
set errormax1=    未找到记录关卡数量最大值的文件。
set errormax2=    关卡数量最大值将使用默认的11100。
set errormax3=    您也可以稍后手动打开UpdateLevelMaxNumber.bat
set errormax4=    来在线检测关卡数量最大值...
set errormax5=    按下任意键继续...
set msg01=      ----SM4J 世界随机器 v3.1----
set msg015=  ----SM4J 世界随机器 v3.1----
set msg02=            By Bilibili 是一刀斩哒
set msg03=      按下任意键来生成一个16随机关卡的世界，
set msg35=      关卡为SM4J Altervista（官网）的随机关卡，
set msg04=      将保存至SM4J游戏内。
set msg05=      请确保电脑联网，
set msg06=      生成速度根据网速而定。
set msg07= 正在下载关卡......
set msg075= 下载关卡
set msg08=下载失败，正在重试...
set msg09=已下载关卡
set msg11= 正在生成世界地图...
set msg12=      生成完成！
set msg13=正在整理文件...
set msg14=      生成的世界名字是：
set msg15=      感谢您使用本软件！
set msg16=      按任意键退出....
set genmsg01=THIS WORLD WAS GENERATED BY 4JRANDOMIZER,
set genmsg02=A TOOL MADE BY YIDAOZHAN_YA
set genmsg03=THANKS FOR PLAYING!
set genmsg04=the end
goto start1

:lang2
chcp 437>nul 2>nul||goto lang3
mode con cols=70 lines=15
set lang=1
set msgtitle=SM4J - World Randomizer V3.1
set errormax1=   No file that records level max number is detected,
set errormax2=   The maximum number of levels will use the default value of 11100,
set errormax3=   You can also run UpdateLevelMaxNumber.bat later
set errormax4=   to manually update the maximum number of levels.
set errormax5=   Press any key to continue...
set msglang=   Multi-language version uses Google translate, may not be accurate
set msg01=      ----SM4J World Randomizer V3.1----
set msg015=  ----SM4J World Randomizer V3.1----
set msg02=            By Yidaozhan_Ya
set msg03=      Press any key to generate a random 16-level world,
set msg35=      Levels are from SM4J Altervista (official),
set msg04=      The generated world will be saved in SM4J.
set msg05=      Please make sure to be online！
set msg06=      This may takes a long time.
set msg07= Fetching level......
set msg075= Downloading Level 
set msg08=Couldn't download the level, retrying...
set msg09=Downloaded level
set msg10=Cleaning up possible error files...
set msg11= Generating worldmap......
set msg12=    Generate Complete！
set msg13=Organizing files...
set msg14=    The generated world name is：
set msg15=    Thank you for using this software！
set msg16=    Press any key to exit....
set genmsg01=THIS WORLD WAS GENERATED BY 4JRANDOMIZER,
set genmsg02=A TOOL MADE BY YIDAOZHAN_YA
set genmsg03=THANKS FOR PLAYING!
set genmsg04=the end
goto start1

:lang3
mode con cols=75 lines=15
set lang=2
set msglang=     La version en varios idiomas utiliza el traductor de Google,
set msglang2=     puede que no sea precisa
set msgtitle=SM4J - Aleatorizador mundial V3.1
set errormax1=  No se detecta ningun archivo que registre el numero maximo de nivel,
set errormax2=  El numero maximo de niveles utilizara el valor predeterminado de 11100,
set errormax3=  Tambien puede ejecutar manualmente UpdateLevelMaxNumber.bat mas tarde
set errormax4=  para actualizar manualmente el numero maximo de niveles.
set errormax5=  Pulse cualquier tecla para continuar...
set msg01=      ----SM4J Aleatorizador mundial V3.1----
set msg015=  ----SM4J Aleatorizador mundial V3.1----
set msg02=            Por Yidaozhan_Ya
set msg03=      Presione cualquier tecla para generar un 16-nivel mundo,
set msg35=      Los niveles son de SM4J Altervista (oficial),
set msg04=      El mundo generado se guardara en SM4J.
set msg05=      Asegurate de estar en linea！
set msg06=      Esto puede llevar mucho tiempo.
set msg07= Descargando Niveles......
set msg075= Descargando Nivel 
set msg08=No se pudo descargar el nivel,volviendo a intentarlo...
set msg09=Nivel descargado
set msg10=Limpiar posibles archivos de error...
set msg11=Generando mapa del mundo ......
set msg12=    Generar completo！
set msg13=Organizar archivos...
set msg14=    El nombre mundial generado es：
set msg15=    Gracias por usar este software！
set msg16=    presiona cualquier tecla para salir....
set genmsg01=ESTE MUNDO FUE GENERADO POR 4J ALEATORIZADOR,
set genmsg02=UNA HERRAMIENTA HECHA POR YIDAOZHAN_YA
set genmsg03=GRACIAS POR JUGAR!
set genmsg04=el fin
goto start1


:start1
title %msgtitle%
if not exist cfg goto errormax
if not exist cfg\maxnumber.cfg goto errormax
echo.&echo.%msg01%
echo.          
echo.%msg02%
echo.&echo.%msg03%
echo.%msg35%
echo.%msg04%
echo.%msg05%
echo.%msg06%
if "%lang%"=="1" echo.&echo.&echo.%msglang%
if "%lang%"=="2" echo.&echo.%msglang%&echo.%msglang2%
pause>nul
del "%~dp0tmp.txt"
rd /s /q mundo
cls
set /p max=<cfg/maxnumber.cfg
set /a max2=%max%-15
md mundo
cls


:lvl1
echo.%msg015%
echo.%msg07%
echo. [▌　　　　　　　　　]5％
echo.%msg075%1...
set /a lvl1=!random!%%!max2!+15
set levelid=%lvl1%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl1
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl1
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel1_id%levelid%.lvl">nul
set level_01=%titler% ID%levelid%
cls

:lvl2
echo.%msg015%
echo.%msg07%
echo. [█　　　　　　　　　]10％
echo.%msg075%2... (2/16)
set /a lvl2=!random!%%!max2!+15
if "%lvl1%"=="%lvl2%" goto lvl2
set levelid=%lvl2%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl2
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl2
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel2_id%levelid%.lvl">nul
set level_02=%titler% ID%levelid%
cls

:lvl3
echo.%msg015%
echo.%msg07%
echo. [█▌　　　　　　　　]15％
echo.%msg075%3... (3/16)
set /a lvl3=!random!%%!max2!+15
if "%lvl3%"=="%lvl1%" goto lvl3
if "%lvl3%"=="%lvl2%" goto lvl3
set levelid=%lvl3%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl3
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl3
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel3_id%levelid%.lvl">nul
set level_03=%titler% ID%levelid%
cls

:lvl4
echo.%msg015%
echo.%msg07%
echo. [██　　　　　　　　]20％
echo.%msg075%4... (4/16)
set /a lvl4=!random!%%!max2!+15
if "%lvl4%"=="%lvl1%" goto lvl4
if "%lvl4%"=="%lvl2%" goto lvl4
if "%lvl4%"=="%lvl3%" goto lvl4
set levelid=%lvl4%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl4
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl4
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel4_id%levelid%.lvl">nul
set level_04=%titler% ID%levelid%
cls


:lvl5
echo.%msg015%
echo.%msg07%
echo. [██▌　　　　　　　]25％
echo.%msg075%5... (5/16)
set /a lvl5=!random!%%!max2!+15
if "%lvl5%"=="%lvl1%" goto lvl5
if "%lvl5%"=="%lvl2%" goto lvl5
if "%lvl5%"=="%lvl3%" goto lvl5
if "%lvl5%"=="%lvl4%" goto lvl5
set levelid=%lvl5%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl5
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl5
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel5_id%levelid%.lvl">nul
set level_05=%titler% ID%levelid%
cls

:lvl6
echo.%msg015%
echo.%msg07%
echo. [███　　　　　　　]30％
echo.%msg075%6... (6/16)
set /a lvl6=!random!%%!max2!+15
if "%lvl6%"=="%lvl1%" goto lvl6
if "%lvl6%"=="%lvl2%" goto lvl6
if "%lvl6%"=="%lvl3%" goto lvl6
if "%lvl6%"=="%lvl4%" goto lvl6
if "%lvl6%"=="%lvl5%" goto lvl6
set levelid=%lvl6%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl6
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl6
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel6_id%levelid%.lvl">nul
set level_06=%titler% ID%levelid%
cls

:lvl7
echo.%msg015%
echo.%msg07%
echo. [███▌　　　　　　]35％
echo.%msg075%7... (7/16)
set /a lvl7=!random!%%!max2!+15
if "%lvl7%"=="%lvl1%" goto lvl7
if "%lvl7%"=="%lvl2%" goto lvl7
if "%lvl7%"=="%lvl3%" goto lvl7
if "%lvl7%"=="%lvl4%" goto lvl7
if "%lvl7%"=="%lvl5%" goto lvl7
if "%lvl7%"=="%lvl6%" goto lvl7
set levelid=%lvl7%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl7
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl7
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel7_id%levelid%.lvl">nul
set level_07=%titler% ID%levelid%
cls

:lvl8
echo.%msg015%
echo.%msg07%
echo. [████　　　　　　]40％
echo.%msg075%8... (8/16)
set /a lvl8=!random!%%!max2!+15
if "%lvl8%"=="%lvl1%" goto lvl8
if "%lvl8%"=="%lvl2%" goto lvl8
if "%lvl8%"=="%lvl3%" goto lvl8
if "%lvl8%"=="%lvl4%" goto lvl8
if "%lvl8%"=="%lvl5%" goto lvl8
if "%lvl8%"=="%lvl6%" goto lvl8
if "%lvl8%"=="%lvl7%" goto lvl8
set levelid=%lvl8%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl8
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl8
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel8_id%levelid%.lvl">nul
set level_08=%titler% ID%levelid%
cls

:lvl9
echo.%msg015%
echo.%msg07%
echo. [████▌　　　　　]45％
echo.%msg075%9... (9/16)
set /a lvl9=!random!%%!max2!+15
if "%lvl9%"=="%lvl1%" goto lvl9
if "%lvl9%"=="%lvl2%" goto lvl9
if "%lvl9%"=="%lvl3%" goto lvl9
if "%lvl9%"=="%lvl4%" goto lvl9
if "%lvl9%"=="%lvl5%" goto lvl9
if "%lvl9%"=="%lvl6%" goto lvl9
if "%lvl9%"=="%lvl7%" goto lvl9
if "%lvl9%"=="%lvl8%" goto lvl9
set levelid=%lvl9%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl9
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl9
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel9_id%levelid%.lvl">nul
set level_09=%titler% ID%levelid%
cls

:lvl10
echo.%msg015%
echo.%msg07%
echo. [█████　　　　　]50％
echo.%msg075%10... (10/16)
set /a lvl10=!random!%%!max2!+15
if "%lvl10%"=="%lvl1%" goto lvl10
if "%lvl10%"=="%lvl2%" goto lvl10
if "%lvl10%"=="%lvl3%" goto lvl10
if "%lvl10%"=="%lvl4%" goto lvl10
if "%lvl10%"=="%lvl5%" goto lvl10
if "%lvl10%"=="%lvl6%" goto lvl10
if "%lvl10%"=="%lvl7%" goto lvl10
if "%lvl10%"=="%lvl8%" goto lvl10
if "%lvl10%"=="%lvl9%" goto lvl10
set levelid=%lvl10%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl10
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl10
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel10_id%levelid%.lvl">nul
set level_10=%titler% ID%levelid%
cls

:lvl11
echo.%msg015%
echo.%msg07%
echo. [█████▌　　　　]55％
echo.%msg075%11... (11/16)
set /a lvl11=!random!%%!max2!+15
if "%lvl11%"=="%lvl1%" goto lvl11
if "%lvl11%"=="%lvl2%" goto lvl11
if "%lvl11%"=="%lvl3%" goto lvl11
if "%lvl11%"=="%lvl4%" goto lvl11
if "%lvl11%"=="%lvl5%" goto lvl11
if "%lvl11%"=="%lvl6%" goto lvl11
if "%lvl11%"=="%lvl7%" goto lvl11
if "%lvl11%"=="%lvl8%" goto lvl11
if "%lvl11%"=="%lvl9%" goto lvl11
if "%lvl11%"=="%lvl10%" goto lvl11
set levelid=%lvl11%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl11
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl11
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel11_id%levelid%.lvl">nul
set level_11=%titler% ID%levelid%
cls

:lvl12
echo.%msg015%
echo.%msg07%
echo. [██████　　　　]60％
echo.%msg075%12... (12/16)
set /a lvl12=!random!%%!max2!+15
if "%lvl12%"=="%lvl1%" goto lvl12
if "%lvl12%"=="%lvl2%" goto lvl12
if "%lvl12%"=="%lvl3%" goto lvl12
if "%lvl12%"=="%lvl4%" goto lvl12
if "%lvl12%"=="%lvl5%" goto lvl12
if "%lvl12%"=="%lvl6%" goto lvl12
if "%lvl12%"=="%lvl7%" goto lvl12
if "%lvl12%"=="%lvl8%" goto lvl12
if "%lvl12%"=="%lvl9%" goto lvl12
if "%lvl12%"=="%lvl10%" goto lvl12
if "%lvl12%"=="%lvl11%" goto lvl12
set levelid=%lvl12%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl12
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl12
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel12_id%levelid%.lvl">nul
set level_12=%titler% ID%levelid%
cls

:lvl13
echo.%msg015%
echo.%msg07%
echo. [██████▌　　　]65％
echo.%msg075%13... (13/16)
set /a lvl13=!random!%%!max2!+15
if "%lvl13%"=="%lvl1%" goto lvl13
if "%lvl13%"=="%lvl2%" goto lvl13
if "%lvl13%"=="%lvl3%" goto lvl13
if "%lvl13%"=="%lvl4%" goto lvl13
if "%lvl13%"=="%lvl5%" goto lvl13
if "%lvl13%"=="%lvl6%" goto lvl13
if "%lvl13%"=="%lvl7%" goto lvl13
if "%lvl13%"=="%lvl8%" goto lvl13
if "%lvl13%"=="%lvl9%" goto lvl13
if "%lvl13%"=="%lvl10%" goto lvl13
if "%lvl13%"=="%lvl11%" goto lvl13
if "%lvl13%"=="%lvl12%" goto lvl13
set levelid=%lvl13%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl13
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl13
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel13_id%levelid%.lvl">nul
set level_13=%titler% ID%levelid%
cls

:lvl14
echo.%msg015%
echo.%msg07%
echo. [███████　　　]70％
echo.%msg075%14... (14/16)
set /a lvl14=!random!%%!max2!+15
if "%lvl14%"=="%lvl1%" goto lvl14
if "%lvl14%"=="%lvl2%" goto lvl14
if "%lvl14%"=="%lvl3%" goto lvl14
if "%lvl14%"=="%lvl4%" goto lvl14
if "%lvl14%"=="%lvl5%" goto lvl14
if "%lvl14%"=="%lvl6%" goto lvl14
if "%lvl14%"=="%lvl7%" goto lvl14
if "%lvl14%"=="%lvl8%" goto lvl14
if "%lvl14%"=="%lvl9%" goto lvl14
if "%lvl14%"=="%lvl10%" goto lvl14
if "%lvl14%"=="%lvl11%" goto lvl14
if "%lvl14%"=="%lvl12%" goto lvl14
if "%lvl14%"=="%lvl13%" goto lvl14
set levelid=%lvl14%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl14
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl14
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel14_id%levelid%.lvl">nul
set level_14=%titler% ID%levelid%
cls

:lvl15
echo.%msg015%
echo.%msg07%
echo. [███████▌　　]75％
echo.%msg075%15... (15/16)
set /a lvl15=!random!%%!max2!+15
if "%lvl15%"=="%lvl1%" goto lvl15
if "%lvl15%"=="%lvl2%" goto lvl15
if "%lvl15%"=="%lvl3%" goto lvl15
if "%lvl15%"=="%lvl4%" goto lvl15
if "%lvl15%"=="%lvl5%" goto lvl15
if "%lvl15%"=="%lvl6%" goto lvl15
if "%lvl15%"=="%lvl7%" goto lvl15
if "%lvl15%"=="%lvl8%" goto lvl15
if "%lvl15%"=="%lvl9%" goto lvl15
if "%lvl15%"=="%lvl10%" goto lvl15
if "%lvl15%"=="%lvl11%" goto lvl15
if "%lvl15%"=="%lvl12%" goto lvl15
if "%lvl15%"=="%lvl13%" goto lvl15
if "%lvl15%"=="%lvl14%" goto lvl15
set levelid=%lvl15%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl15
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl15
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel15_id%levelid%.lvl">nul
set level_15=%titler% ID%levelid%
cls

:lvl16
echo.%msg015%
echo.%msg07%
echo. [█████████　]90％
set /a lvl16=!random!%%!max2!+15
if "%lvl16%"=="%lvl1%" goto lvl16
if "%lvl16%"=="%lvl2%" goto lvl16
if "%lvl16%"=="%lvl3%" goto lvl16
if "%lvl16%"=="%lvl4%" goto lvl16
if "%lvl16%"=="%lvl5%" goto lvl16
if "%lvl16%"=="%lvl6%" goto lvl16
if "%lvl16%"=="%lvl7%" goto lvl16
if "%lvl16%"=="%lvl8%" goto lvl16
if "%lvl16%"=="%lvl9%" goto lvl16
if "%lvl16%"=="%lvl10%" goto lvl16
if "%lvl16%"=="%lvl11%" goto lvl16
if "%lvl16%"=="%lvl12%" goto lvl16
if "%lvl16%"=="%lvl13%" goto lvl16
if "%lvl16%"=="%lvl14%" goto lvl16
if "%lvl16%"=="%lvl15%" goto lvl16
set levelid=%lvl16%
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/file.php?id=%levelid%"
ren "%~dp0file.php@id=%levelid%" tmp.txt
for /f "tokens=1,* delims=:-" %%a in ('findstr /n .* tmp.txt') do (
   if "%%a"=="6" echo %%b>tmp.txt
)
for /f "tokens=1-3 delims=-" %%a in (tmp.txt) do (
set titler=%%c
)
set titler=%titler:</title>=%
del "%~dp0tmp.txt"
set "titler=%titler:* =%"
if "%titler%"=="Invalid File" echo.%msg08% & cls & goto lvl16
wget -q -P "%cd%" "https://carlosxdjavgames.altervista.org/wp-content/data_extra/%titler%%levelid%.lvl"
if not exist "%~dp0%titler%%levelid%.lvl" (
echo.%msg08% & cls
goto lvl16
)
move "%~dp0%titler%%levelid%.lvl" "%~dp0mundo/nivel16_id%levelid%.lvl">nul
set level_16=%titler% ID%levelid%
cls

echo.%msg015%
echo.%msg11%
echo. [█████████▌]95％
echo.
del "%~dp0*.lvl"
del "%~dp0tmp.txt"
del "%~dp0file.php*"
echo.%msg11%
dir /b "%~dp0mundo" >temp2.log
for /f "tokens=1 delims=." %%i in (temp2.log) do (
    set/a n+=1
    if !n! equ 1 set nivel1=%%i
    if !n! equ 2 set nivel2=%%i
    if !n! equ 3 set nivel3=%%i
    if !n! equ 4 set nivel4=%%i
    if !n! equ 5 set nivel5=%%i
    if !n! equ 6 set nivel6=%%i
    if !n! equ 7 set nivel7=%%i
    if !n! equ 8 set nivel8=%%i
    if !n! equ 9 set nivel9=%%i
    if !n! equ 10 set nivel10=%%i
    if !n! equ 11 set nivel11=%%i
    if !n! equ 12 set nivel12=%%i
    if !n! equ 13 set nivel13=%%i
    if !n! equ 14 set nivel14=%%i
    if !n! equ 15 set nivel15=%%i
    if !n! equ 16 set nivel16=%%i
)
set mundoname=SM4JWorld_%random%
set mod3=3
set /a theme=!random!%%!mod3!+1
if "%theme%"=="1" set themename=GrassLand
if "%theme%"=="2" set themename=Desert
if "%theme%"=="3" set themename=Ice
set mod3=17
set /a music=!random!%%!mod3!+1
if "%music%"=="1" set mapmusic=26
if "%music%"=="2" set mapmusic=1
if "%music%"=="3" set mapmusic=17
if "%music%"=="4" set mapmusic=25
if "%music%"=="5" set mapmusic=29
if "%music%"=="6" set mapmusic=30
if "%music%"=="7" set mapmusic=31
if "%music%"=="8" set mapmusic=32
if "%music%"=="9" set mapmusic=33
if "%music%"=="10" set mapmusic=35
if "%music%"=="11" set mapmusic=38
if "%music%"=="12" set mapmusic=43
if "%music%"=="13" set mapmusic=45
if "%music%"=="13" set mapmusic=45
if "%music%"=="15" set mapmusic=52
if "%music%"=="16" set mapmusic=53
if "%music%"=="17" set mapmusic=59
if "%theme%"=="1" goto theme1
if "%theme%"=="2" goto theme2
if "%theme%"=="3" goto theme3

:theme1
set worldtile=obj_WE_tile2_Colocado
set mapmushroom=obj_WE_mapmushroom_Colocado
set mapflower=obj_WE_mapmushroom_Colocado
set mappiant=obj_WE_mapflower_Colocado
set mappalm=obj_WE_mapflower_Colocado
set maphills=obj_WE_maphills_Colocado
goto worldgenerate

:theme2
set worldtile=obj_WE_tile1_Colocado
set mapmushroom=obj_WE_mappalm_Colocado
set maphills=obj_WE_mappalm_Colocado
set mapflower=obj_WE_mapfire_Colocado
set mappiant=obj_WE_mappiramid_Colocado
set mappalm=obj_WE_mappiramid_Colocado
goto worldgenerate

:theme3
set worldtile=obj_WE_tile3_Colocado
set mapmushroom=obj_WE_mapice_Colocado
set maphills=obj_WE_solid_Colocado
set mapflower=obj_WE_mapice_Colocado
set mappiant=obj_WE_mapice_Colocado
set mappalm=obj_WE_mapice_Colocado
goto worldgenerate

:worldgenerate
echo.[options]>>%mundoname%.wrl
echo.lobby_enabled="off">>%mundoname%.wrl
echo.lobby_name="level.lvl">>%mundoname%.wrl
echo.room_y="432.000000">>%mundoname%.wrl
echo.room_x="2048.000000">>%mundoname%.wrl
echo.mapas="1.000000">>%mundoname%.wrl
echo.tiempo_count="300.000000">>%mundoname%.wrl
echo.tiempo="off">>%mundoname%.wrl
echo.mario_y="128.000000">>%mundoname%.wrl
echo.mario_x="112.000000">>%mundoname%.wrl
echo.storm="off">>%mundoname%.wrl
echo.modo="1.000000">>%mundoname%.wrl
echo.musica_le="163.000000">>%mundoname%.wrl
echo.musica="%mapmusic%.000000">>%mundoname%.wrl
echo.bg="1.000000">>%mundoname%.wrl
echo.background="114.000000">>%mundoname%.wrl
echo.[colocado9]>>%mundoname%.wrl
echo.104="1">>%mundoname%.wrl
echo.103="1">>%mundoname%.wrl
echo.102="224">>%mundoname%.wrl
echo.101="96">>%mundoname%.wrl
echo.100="obj_LE_solid">>%mundoname%.wrl
echo.94="1">>%mundoname%.wrl
echo.93="-11">>%mundoname%.wrl
echo.92="240">>%mundoname%.wrl
echo.91="288">>%mundoname%.wrl
echo.90="obj_LE_solid">>%mundoname%.wrl
echo.84="4">>%mundoname%.wrl
echo.83="1">>%mundoname%.wrl
echo.82="192">>%mundoname%.wrl
echo.81="288">>%mundoname%.wrl
echo.80="obj_LE_solid">>%mundoname%.wrl
echo.74="1">>%mundoname%.wrl
echo.73="10">>%mundoname%.wrl
echo.72="208">>%mundoname%.wrl
echo.71="112">>%mundoname%.wrl
echo.70="obj_LE_solid">>%mundoname%.wrl
echo.64="5">>%mundoname%.wrl
echo.63="1">>%mundoname%.wrl
echo.62="144">>%mundoname%.wrl
echo.61="96">>%mundoname%.wrl
echo.60="obj_LE_solid">>%mundoname%.wrl
echo.54="1">>%mundoname%.wrl
echo.53="-10">>%mundoname%.wrl
echo.52="176">>%mundoname%.wrl
echo.51="288">>%mundoname%.wrl
echo.50="obj_LE_solid">>%mundoname%.wrl
echo.44="4">>%mundoname%.wrl
echo.43="1">>%mundoname%.wrl
echo.42="128">>%mundoname%.wrl
echo.41="288">>%mundoname%.wrl
echo.40="obj_LE_solid">>%mundoname%.wrl
echo.34="1">>%mundoname%.wrl
echo.33="1">>%mundoname%.wrl
echo.32="112">>%mundoname%.wrl
echo.31="272">>%mundoname%.wrl
echo.30="obj_LE_solid">>%mundoname%.wrl
echo.24="1">>%mundoname%.wrl
echo.23="10">>%mundoname%.wrl
echo.22="112">>%mundoname%.wrl
echo.21="112">>%mundoname%.wrl
echo.20="obj_LE_solid">>%mundoname%.wrl
echo.14="1">>%mundoname%.wrl
echo.13="10">>%mundoname%.wrl
echo.12="144">>%mundoname%.wrl
echo.11="112">>%mundoname%.wrl
echo.10="obj_LE_solid">>%mundoname%.wrl
echo.04="1">>%mundoname%.wrl
echo.03="1">>%mundoname%.wrl
echo.02="128">>%mundoname%.wrl
echo.01="96">>%mundoname%.wrl
echo.00="obj_LE_solid">>%mundoname%.wrl
echo.[colocado3]>>%mundoname%.wrl
echo.164="1.000000">>%mundoname%.wrl
echo.163="theend">>%mundoname%.wrl
echo.162="224.000000">>%mundoname%.wrl
echo.161="112.000000">>%mundoname%.wrl
echo.160="obj_WE_boohouse_Colocado">>%mundoname%.wrl
echo.154="1.000000">>%mundoname%.wrl
echo.153="%nivel16%">>%mundoname%.wrl
echo.152="224.000000">>%mundoname%.wrl
echo.151="144.000000">>%mundoname%.wrl
echo.150="obj_WE_bowsercastle_Colocado">>%mundoname%.wrl
echo.144="15.000000">>%mundoname%.wrl
echo.143="%nivel15%">>%mundoname%.wrl
echo.142="224.000000">>%mundoname%.wrl
echo.141="176.000000">>%mundoname%.wrl
echo.140="obj_WE_world_4Colocado">>%mundoname%.wrl
echo.134="14.000000">>%mundoname%.wrl
echo.133="%nivel14%">>%mundoname%.wrl
echo.132="224.000000">>%mundoname%.wrl
echo.131="208.000000">>%mundoname%.wrl
echo.130="obj_WE_world_4Colocado">>%mundoname%.wrl
echo.124="13.000000">>%mundoname%.wrl
echo.123="%nivel13%">>%mundoname%.wrl
echo.122="224.000000">>%mundoname%.wrl
echo.121="240.000000">>%mundoname%.wrl
echo.120="obj_WE_world_4Colocado">>%mundoname%.wrl
echo.114="12.000000">>%mundoname%.wrl
echo.113="%nivel12%">>%mundoname%.wrl
echo.112="192.000000">>%mundoname%.wrl
echo.111="240.000000">>%mundoname%.wrl
echo.110="obj_WE_world_3Colocado">>%mundoname%.wrl
echo.104="11.000000">>%mundoname%.wrl
echo.103="%nivel11%">>%mundoname%.wrl
echo.102="192.000000">>%mundoname%.wrl
echo.101="208.000000">>%mundoname%.wrl
echo.100="obj_WE_world_3Colocado">>%mundoname%.wrl
echo.94="10.000000">>%mundoname%.wrl
echo.93="%nivel10%">>%mundoname%.wrl
echo.92="192.000000">>%mundoname%.wrl
echo.91="176.000000">>%mundoname%.wrl
echo.90="obj_WE_world_3Colocado">>%mundoname%.wrl
echo.84="9.000000">>%mundoname%.wrl
echo.83="%nivel9%">>%mundoname%.wrl
echo.82="192.000000">>%mundoname%.wrl
echo.81="144.000000">>%mundoname%.wrl
echo.80="obj_WE_world_3Colocado">>%mundoname%.wrl
echo.74="8.000000">>%mundoname%.wrl
echo.73="%nivel8%">>%mundoname%.wrl
echo.72="160.000000">>%mundoname%.wrl
echo.71="144.000000">>%mundoname%.wrl
echo.70="obj_WE_world_2Colocado">>%mundoname%.wrl
echo.64="7.000000">>%mundoname%.wrl
echo.63="%nivel7%">>%mundoname%.wrl
echo.62="160.000000">>%mundoname%.wrl
echo.61="176.000000">>%mundoname%.wrl
echo.60="obj_WE_world_2Colocado">>%mundoname%.wrl
echo.54="6.000000">>%mundoname%.wrl
echo.53="%nivel6%">>%mundoname%.wrl
echo.52="160.000000">>%mundoname%.wrl
echo.51="208.000000">>%mundoname%.wrl
echo.50="obj_WE_world_2Colocado">>%mundoname%.wrl
echo.44="5.000000">>%mundoname%.wrl
echo.43="%nivel5%">>%mundoname%.wrl
echo.42="160.000000">>%mundoname%.wrl
echo.41="240.000000">>%mundoname%.wrl
echo.40="obj_WE_world_2Colocado">>%mundoname%.wrl
echo.34="4.000000">>%mundoname%.wrl
echo.33="%nivel4%">>%mundoname%.wrl
echo.32="128.000000">>%mundoname%.wrl
echo.31="240.000000">>%mundoname%.wrl
echo.30="obj_WE_worldColocado">>%mundoname%.wrl
echo.24="3.000000">>%mundoname%.wrl
echo.23="%nivel3%">>%mundoname%.wrl
echo.22="128.000000">>%mundoname%.wrl
echo.21="208.000000">>%mundoname%.wrl
echo.20="obj_WE_worldColocado">>%mundoname%.wrl
echo.14="2.000000">>%mundoname%.wrl
echo.13="%nivel2%">>%mundoname%.wrl
echo.12="128.000000">>%mundoname%.wrl
echo.11="176.000000">>%mundoname%.wrl
echo.10="obj_WE_worldColocado">>%mundoname%.wrl
echo.04="1.000000">>%mundoname%.wrl
echo.03="%nivel1%">>%mundoname%.wrl
echo.02="128.000000">>%mundoname%.wrl
echo.01="144.000000">>%mundoname%.wrl
echo.00="obj_WE_worldColocado">>%mundoname%.wrl
echo.[colocado2]>>%mundoname%.wrl
echo.442="224.000000">>%mundoname%.wrl
echo.441="176.000000">>%mundoname%.wrl
echo.440="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.432="224.000000">>%mundoname%.wrl
echo.431="208.000000">>%mundoname%.wrl
echo.430="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.422="224.000000">>%mundoname%.wrl
echo.421="240.000000">>%mundoname%.wrl
echo.420="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.412="192.000000">>%mundoname%.wrl
echo.411="240.000000">>%mundoname%.wrl
echo.410="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.402="192.000000">>%mundoname%.wrl
echo.401="208.000000">>%mundoname%.wrl
echo.400="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.392="192.000000">>%mundoname%.wrl
echo.391="176.000000">>%mundoname%.wrl
echo.390="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.382="192.000000">>%mundoname%.wrl
echo.381="144.000000">>%mundoname%.wrl
echo.380="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.372="160.000000">>%mundoname%.wrl
echo.371="144.000000">>%mundoname%.wrl
echo.370="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.362="160.000000">>%mundoname%.wrl
echo.361="176.000000">>%mundoname%.wrl
echo.360="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.352="160.000000">>%mundoname%.wrl
echo.351="208.000000">>%mundoname%.wrl
echo.350="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.342="160.000000">>%mundoname%.wrl
echo.341="240.000000">>%mundoname%.wrl
echo.340="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.332="128.000000">>%mundoname%.wrl
echo.331="240.000000">>%mundoname%.wrl
echo.330="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.322="128.000000">>%mundoname%.wrl
echo.321="144.000000">>%mundoname%.wrl
echo.320="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.312="128.000000">>%mundoname%.wrl
echo.311="176.000000">>%mundoname%.wrl
echo.310="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.302="128.000000">>%mundoname%.wrl
echo.301="208.000000">>%mundoname%.wrl
echo.300="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.292="224.000000">>%mundoname%.wrl
echo.291="112.000000">>%mundoname%.wrl
echo.290="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.282="192.000000">>%mundoname%.wrl
echo.281="112.000000">>%mundoname%.wrl
echo.280="obj_WE_ph_V_Colocado">>%mundoname%.wrl
echo.272="176.000000">>%mundoname%.wrl
echo.271="112.000000">>%mundoname%.wrl
echo.270="obj_WE_ph_V_Colocado">>%mundoname%.wrl
echo.262="224.000000">>%mundoname%.wrl
echo.261="128.000000">>%mundoname%.wrl
echo.260="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.252="128.000000">>%mundoname%.wrl
echo.251="128.000000">>%mundoname%.wrl
echo.250="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.242="160.000000">>%mundoname%.wrl
echo.241="128.000000">>%mundoname%.wrl
echo.240="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.232="192.000000">>%mundoname%.wrl
echo.231="128.000000">>%mundoname%.wrl
echo.230="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.222="224.000000">>%mundoname%.wrl
echo.221="144.000000">>%mundoname%.wrl
echo.220="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.212="128.000000">>%mundoname%.wrl
echo.211="160.000000">>%mundoname%.wrl
echo.210="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.202="160.000000">>%mundoname%.wrl
echo.201="160.000000">>%mundoname%.wrl
echo.200="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.192="224.000000">>%mundoname%.wrl
echo.191="160.000000">>%mundoname%.wrl
echo.190="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.182="192.000000">>%mundoname%.wrl
echo.181="160.000000">>%mundoname%.wrl
echo.180="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.172="128.000000">>%mundoname%.wrl
echo.171="192.000000">>%mundoname%.wrl
echo.170="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.162="160.000000">>%mundoname%.wrl
echo.161="192.000000">>%mundoname%.wrl
echo.160="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.152="224.000000">>%mundoname%.wrl
echo.151="192.000000">>%mundoname%.wrl
echo.150="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.142="192.000000">>%mundoname%.wrl
echo.141="192.000000">>%mundoname%.wrl
echo.140="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.132="128.000000">>%mundoname%.wrl
echo.131="256.000000">>%mundoname%.wrl
echo.130="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.122="128.000000">>%mundoname%.wrl
echo.121="224.000000">>%mundoname%.wrl
echo.120="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.112="144.000000">>%mundoname%.wrl
echo.111="272.000000">>%mundoname%.wrl
echo.110="obj_WE_ph_V_Colocado">>%mundoname%.wrl
echo.102="160.000000">>%mundoname%.wrl
echo.101="272.000000">>%mundoname%.wrl
echo.100="obj_WE_ph_V_Colocado">>%mundoname%.wrl
echo.92="160.000000">>%mundoname%.wrl
echo.91="272.000000">>%mundoname%.wrl
echo.90="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.82="160.000000">>%mundoname%.wrl
echo.81="256.000000">>%mundoname%.wrl
echo.80="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.72="160.000000">>%mundoname%.wrl
echo.71="224.000000">>%mundoname%.wrl
echo.70="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.62="224.000000">>%mundoname%.wrl
echo.61="272.000000">>%mundoname%.wrl
echo.60="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.52="224.000000">>%mundoname%.wrl
echo.51="272.000000">>%mundoname%.wrl
echo.50="obj_WE_ph_V_Colocado">>%mundoname%.wrl
echo.42="208.000000">>%mundoname%.wrl
echo.41="272.000000">>%mundoname%.wrl
echo.40="obj_WE_ph_V_Colocado">>%mundoname%.wrl
echo.32="224.000000">>%mundoname%.wrl
echo.31="224.000000">>%mundoname%.wrl
echo.30="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.22="224.000000">>%mundoname%.wrl
echo.21="256.000000">>%mundoname%.wrl
echo.20="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.12="192.000000">>%mundoname%.wrl
echo.11="256.000000">>%mundoname%.wrl
echo.10="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.02="192.000000">>%mundoname%.wrl
echo.01="224.000000">>%mundoname%.wrl
echo.00="obj_WE_ph_H_Colocado">>%mundoname%.wrl
echo.[colocado]>>%mundoname%.wrl
echo.1522="128.000000">>%mundoname%.wrl
echo.1521="96.000000">>%mundoname%.wrl
echo.1520="%maphills%">>%mundoname%.wrl
echo.1512="160.000000">>%mundoname%.wrl
echo.1511="96.000000">>%mundoname%.wrl
echo.1510="%mapmushroom%">>%mundoname%.wrl
echo.1502="192.000000">>%mundoname%.wrl
echo.1501="96.000000">>%mundoname%.wrl
echo.1500="%mapmushroom%">>%mundoname%.wrl
echo.1492="192.000000">>%mundoname%.wrl
echo.1491="112.000000">>%mundoname%.wrl
echo.1490="obj_WE_mapstop_Colocado">>%mundoname%.wrl
echo.1482="112.000000">>%mundoname%.wrl
echo.1481="128.000000">>%mundoname%.wrl
echo.1480="%maphills%">>%mundoname%.wrl
echo.1472="144.000000">>%mundoname%.wrl
echo.1471="128.000000">>%mundoname%.wrl
echo.1470="%maphills%">>%mundoname%.wrl
echo.1462="208.000000">>%mundoname%.wrl
echo.1461="144.000000">>%mundoname%.wrl
echo.1460="%mapflower%">>%mundoname%.wrl
echo.1452="112.000000">>%mundoname%.wrl
echo.1451="160.000000">>%mundoname%.wrl
echo.1450="%maphills%">>%mundoname%.wrl
echo.1442="144.000000">>%mundoname%.wrl
echo.1441="160.000000">>%mundoname%.wrl
echo.1440="%mapmushroom%">>%mundoname%.wrl
echo.1432="208.000000">>%mundoname%.wrl
echo.1431="176.000000">>%mundoname%.wrl
echo.1430="%mapflower%">>%mundoname%.wrl
echo.1422="112.000000">>%mundoname%.wrl
echo.1421="192.000000">>%mundoname%.wrl
echo.1420="%maphills%">>%mundoname%.wrl
echo.1412="144.000000">>%mundoname%.wrl
echo.1411="192.000000">>%mundoname%.wrl
echo.1410="%mapmushroom%">>%mundoname%.wrl
echo.1402="112.000000">>%mundoname%.wrl
echo.1401="256.000000">>%mundoname%.wrl
echo.1400="%maphills%">>%mundoname%.wrl
echo.1392="112.000000">>%mundoname%.wrl
echo.1391="224.000000">>%mundoname%.wrl
echo.1390="%maphills%">>%mundoname%.wrl
echo.1382="128.000000">>%mundoname%.wrl
echo.1381="288.000000">>%mundoname%.wrl
echo.1380="%maphills%">>%mundoname%.wrl
echo.1372="144.000000">>%mundoname%.wrl
echo.1371="256.000000">>%mundoname%.wrl
echo.1370="%mapmushroom%">>%mundoname%.wrl
echo.1362="144.000000">>%mundoname%.wrl
echo.1361="224.000000">>%mundoname%.wrl
echo.1360="%mapmushroom%">>%mundoname%.wrl
echo.1352="160.000000">>%mundoname%.wrl
echo.1351="288.000000">>%mundoname%.wrl
echo.1350="%mapmushroom%">>%mundoname%.wrl
echo.1342="160.000000">>%mundoname%.wrl
echo.1341="272.000000">>%mundoname%.wrl
echo.1340="obj_WE_mapstop_Colocado">>%mundoname%.wrl
echo.1332="176.000000">>%mundoname%.wrl
echo.1331="288.000000">>%mundoname%.wrl
echo.1330="%mapmushroom%">>%mundoname%.wrl
echo.1322="208.000000">>%mundoname%.wrl
echo.1321="240.000000">>%mundoname%.wrl
echo.1320="%mapflower%">>%mundoname%.wrl
echo.1312="208.000000">>%mundoname%.wrl
echo.1311="208.000000">>%mundoname%.wrl
echo.1310="%mapflower%">>%mundoname%.wrl
echo.1302="176.000000">>%mundoname%.wrl
echo.1301="256.000000">>%mundoname%.wrl
echo.1300="%mapmushroom%">>%mundoname%.wrl
echo.1292="224.000000">>%mundoname%.wrl
echo.1291="272.000000">>%mundoname%.wrl
echo.1290="obj_WE_mapstop_Colocado">>%mundoname%.wrl
echo.1282="176.000000">>%mundoname%.wrl
echo.1281="128.000000">>%mundoname%.wrl
echo.1280="%mappalm%">>%mundoname%.wrl
echo.1272="176.000000">>%mundoname%.wrl
echo.1271="160.000000">>%mundoname%.wrl
echo.1270="%mappalm%">>%mundoname%.wrl
echo.1262="176.000000">>%mundoname%.wrl
echo.1261="192.000000">>%mundoname%.wrl
echo.1260="%mappalm%">>%mundoname%.wrl
echo.1252="176.000000">>%mundoname%.wrl
echo.1251="224.000000">>%mundoname%.wrl
echo.1250="%mappalm%">>%mundoname%.wrl
echo.1242="208.000000">>%mundoname%.wrl
echo.1241="256.000000">>%mundoname%.wrl
echo.1240="%mappiant%">>%mundoname%.wrl
echo.1232="240.000000">>%mundoname%.wrl
echo.1231="224.000000">>%mundoname%.wrl
echo.1230="%mappiant%">>%mundoname%.wrl
echo.1222="240.000000">>%mundoname%.wrl
echo.1221="192.000000">>%mundoname%.wrl
echo.1220="%mappiant%">>%mundoname%.wrl
echo.1212="240.000000">>%mundoname%.wrl
echo.1211="144.000000">>%mundoname%.wrl
echo.1210="%mappiant%">>%mundoname%.wrl
echo.1202="208.000000">>%mundoname%.wrl
echo.1201="112.000000">>%mundoname%.wrl
echo.1200="%mappiant%">>%mundoname%.wrl
echo.1192="224.000000">>%mundoname%.wrl
echo.1191="144.000000">>%mundoname%.wrl
echo.1190="%worldtile%">>%mundoname%.wrl
echo.1182="224.000000">>%mundoname%.wrl
echo.1181="160.000000">>%mundoname%.wrl
echo.1180="%worldtile%">>%mundoname%.wrl
echo.1172="208.000000">>%mundoname%.wrl
echo.1171="160.000000">>%mundoname%.wrl
echo.1170="%worldtile%">>%mundoname%.wrl
echo.1162="128.000000">>%mundoname%.wrl
echo.1161="176.000000">>%mundoname%.wrl
echo.1160="%worldtile%">>%mundoname%.wrl
echo.1152="128.000000">>%mundoname%.wrl
echo.1151="144.000000">>%mundoname%.wrl
echo.1150="%worldtile%">>%mundoname%.wrl
echo.1142="128.000000">>%mundoname%.wrl
echo.1141="208.000000">>%mundoname%.wrl
echo.1140="%worldtile%">>%mundoname%.wrl
echo.1132="224.000000">>%mundoname%.wrl
echo.1131="176.000000">>%mundoname%.wrl
echo.1130="%worldtile%">>%mundoname%.wrl
echo.1122="224.000000">>%mundoname%.wrl
echo.1121="208.000000">>%mundoname%.wrl
echo.1120="%worldtile%">>%mundoname%.wrl
echo.1112="224.000000">>%mundoname%.wrl
echo.1111="240.000000">>%mundoname%.wrl
echo.1110="%worldtile%">>%mundoname%.wrl
echo.1102="128.000000">>%mundoname%.wrl
echo.1101="240.000000">>%mundoname%.wrl
echo.1100="%worldtile%">>%mundoname%.wrl
echo.1092="160.000000">>%mundoname%.wrl
echo.1091="176.000000">>%mundoname%.wrl
echo.1090="%worldtile%">>%mundoname%.wrl
echo.1082="160.000000">>%mundoname%.wrl
echo.1081="240.000000">>%mundoname%.wrl
echo.1080="%worldtile%">>%mundoname%.wrl
echo.1072="192.000000">>%mundoname%.wrl
echo.1071="208.000000">>%mundoname%.wrl
echo.1070="%worldtile%">>%mundoname%.wrl
echo.1062="160.000000">>%mundoname%.wrl
echo.1061="208.000000">>%mundoname%.wrl
echo.1060="%worldtile%">>%mundoname%.wrl
echo.1052="160.000000">>%mundoname%.wrl
echo.1051="144.000000">>%mundoname%.wrl
echo.1050="%worldtile%">>%mundoname%.wrl
echo.1042="192.000000">>%mundoname%.wrl
echo.1041="144.000000">>%mundoname%.wrl
echo.1040="%worldtile%">>%mundoname%.wrl
echo.1032="192.000000">>%mundoname%.wrl
echo.1031="176.000000">>%mundoname%.wrl
echo.1030="%worldtile%">>%mundoname%.wrl
echo.1022="192.000000">>%mundoname%.wrl
echo.1021="240.000000">>%mundoname%.wrl
echo.1020="%worldtile%">>%mundoname%.wrl
echo.1012="112.000000">>%mundoname%.wrl
echo.1011="96.000000">>%mundoname%.wrl
echo.1010="%worldtile%">>%mundoname%.wrl
echo.1002="128.000000">>%mundoname%.wrl
echo.1001="96.000000">>%mundoname%.wrl
echo.1000="%worldtile%">>%mundoname%.wrl
echo.992="144.000000">>%mundoname%.wrl
echo.991="96.000000">>%mundoname%.wrl
echo.990="%worldtile%">>%mundoname%.wrl
echo.982="160.000000">>%mundoname%.wrl
echo.981="96.000000">>%mundoname%.wrl
echo.980="%worldtile%">>%mundoname%.wrl
echo.972="240.000000">>%mundoname%.wrl
echo.971="96.000000">>%mundoname%.wrl
echo.970="%worldtile%">>%mundoname%.wrl
echo.962="224.000000">>%mundoname%.wrl
echo.961="96.000000">>%mundoname%.wrl
echo.960="%worldtile%">>%mundoname%.wrl
echo.952="208.000000">>%mundoname%.wrl
echo.951="96.000000">>%mundoname%.wrl
echo.950="%worldtile%">>%mundoname%.wrl
echo.942="192.000000">>%mundoname%.wrl
echo.941="96.000000">>%mundoname%.wrl
echo.940="%worldtile%">>%mundoname%.wrl
echo.932="176.000000">>%mundoname%.wrl
echo.931="96.000000">>%mundoname%.wrl
echo.930="%worldtile%">>%mundoname%.wrl
echo.922="112.000000">>%mundoname%.wrl
echo.921="112.000000">>%mundoname%.wrl
echo.920="%worldtile%">>%mundoname%.wrl
echo.912="224.000000">>%mundoname%.wrl
echo.911="112.000000">>%mundoname%.wrl
echo.910="%worldtile%">>%mundoname%.wrl
echo.902="128.000000">>%mundoname%.wrl
echo.901="112.000000">>%mundoname%.wrl
echo.900="%worldtile%">>%mundoname%.wrl
echo.892="144.000000">>%mundoname%.wrl
echo.891="112.000000">>%mundoname%.wrl
echo.890="%worldtile%">>%mundoname%.wrl
echo.882="160.000000">>%mundoname%.wrl
echo.881="112.000000">>%mundoname%.wrl
echo.880="obj_WE_mushhousegreenColocado">>%mundoname%.wrl
echo.872="160.000000">>%mundoname%.wrl
echo.871="112.000000">>%mundoname%.wrl
echo.870="%worldtile%">>%mundoname%.wrl
echo.862="192.000000">>%mundoname%.wrl
echo.861="112.000000">>%mundoname%.wrl
echo.860="%worldtile%">>%mundoname%.wrl
echo.852="240.000000">>%mundoname%.wrl
echo.851="112.000000">>%mundoname%.wrl
echo.850="%worldtile%">>%mundoname%.wrl
echo.842="208.000000">>%mundoname%.wrl
echo.841="112.000000">>%mundoname%.wrl
echo.840="%worldtile%">>%mundoname%.wrl
echo.832="176.000000">>%mundoname%.wrl
echo.831="112.000000">>%mundoname%.wrl
echo.830="%worldtile%">>%mundoname%.wrl
echo.822="112.000000">>%mundoname%.wrl
echo.821="128.000000">>%mundoname%.wrl
echo.820="%worldtile%">>%mundoname%.wrl
echo.812="128.000000">>%mundoname%.wrl
echo.811="128.000000">>%mundoname%.wrl
echo.810="%worldtile%">>%mundoname%.wrl
echo.802="144.000000">>%mundoname%.wrl
echo.801="128.000000">>%mundoname%.wrl
echo.800="%worldtile%">>%mundoname%.wrl
echo.792="160.000000">>%mundoname%.wrl
echo.791="128.000000">>%mundoname%.wrl
echo.790="%worldtile%">>%mundoname%.wrl
echo.782="240.000000">>%mundoname%.wrl
echo.781="128.000000">>%mundoname%.wrl
echo.780="%worldtile%">>%mundoname%.wrl
echo.772="208.000000">>%mundoname%.wrl
echo.771="128.000000">>%mundoname%.wrl
echo.770="%worldtile%">>%mundoname%.wrl
echo.762="224.000000">>%mundoname%.wrl
echo.761="128.000000">>%mundoname%.wrl
echo.760="%worldtile%">>%mundoname%.wrl
echo.752="192.000000">>%mundoname%.wrl
echo.751="128.000000">>%mundoname%.wrl
echo.750="%worldtile%">>%mundoname%.wrl
echo.742="112.000000">>%mundoname%.wrl
echo.741="144.000000">>%mundoname%.wrl
echo.740="%worldtile%">>%mundoname%.wrl
echo.732="144.000000">>%mundoname%.wrl
echo.731="144.000000">>%mundoname%.wrl
echo.730="%worldtile%">>%mundoname%.wrl
echo.722="176.000000">>%mundoname%.wrl
echo.721="144.000000">>%mundoname%.wrl
echo.720="%worldtile%">>%mundoname%.wrl
echo.712="240.000000">>%mundoname%.wrl
echo.711="144.000000">>%mundoname%.wrl
echo.710="%worldtile%">>%mundoname%.wrl
echo.702="208.000000">>%mundoname%.wrl
echo.701="144.000000">>%mundoname%.wrl
echo.700="%worldtile%">>%mundoname%.wrl
echo.692="112.000000">>%mundoname%.wrl
echo.691="160.000000">>%mundoname%.wrl
echo.690="%worldtile%">>%mundoname%.wrl
echo.682="128.000000">>%mundoname%.wrl
echo.681="160.000000">>%mundoname%.wrl
echo.680="%worldtile%">>%mundoname%.wrl
echo.672="144.000000">>%mundoname%.wrl
echo.671="160.000000">>%mundoname%.wrl
echo.670="%worldtile%">>%mundoname%.wrl
echo.662="160.000000">>%mundoname%.wrl
echo.661="160.000000">>%mundoname%.wrl
echo.660="%worldtile%">>%mundoname%.wrl
echo.652="192.000000">>%mundoname%.wrl
echo.651="160.000000">>%mundoname%.wrl
echo.650="%worldtile%">>%mundoname%.wrl
echo.642="240.000000">>%mundoname%.wrl
echo.641="160.000000">>%mundoname%.wrl
echo.640="%worldtile%">>%mundoname%.wrl
echo.632="112.000000">>%mundoname%.wrl
echo.631="176.000000">>%mundoname%.wrl
echo.630="%worldtile%">>%mundoname%.wrl
echo.622="144.000000">>%mundoname%.wrl
echo.621="176.000000">>%mundoname%.wrl
echo.620="%worldtile%">>%mundoname%.wrl
echo.612="176.000000">>%mundoname%.wrl
echo.611="176.000000">>%mundoname%.wrl
echo.610="%worldtile%">>%mundoname%.wrl
echo.602="208.000000">>%mundoname%.wrl
echo.601="176.000000">>%mundoname%.wrl
echo.600="%worldtile%">>%mundoname%.wrl
echo.592="240.000000">>%mundoname%.wrl
echo.591="176.000000">>%mundoname%.wrl
echo.590="%worldtile%">>%mundoname%.wrl
echo.582="112.000000">>%mundoname%.wrl
echo.581="192.000000">>%mundoname%.wrl
echo.580="%worldtile%">>%mundoname%.wrl
echo.572="128.000000">>%mundoname%.wrl
echo.571="192.000000">>%mundoname%.wrl
echo.570="%worldtile%">>%mundoname%.wrl
echo.562="144.000000">>%mundoname%.wrl
echo.561="192.000000">>%mundoname%.wrl
echo.560="%worldtile%">>%mundoname%.wrl
echo.552="160.000000">>%mundoname%.wrl
echo.551="192.000000">>%mundoname%.wrl
echo.550="%worldtile%">>%mundoname%.wrl
echo.542="208.000000">>%mundoname%.wrl
echo.541="192.000000">>%mundoname%.wrl
echo.540="%worldtile%">>%mundoname%.wrl
echo.532="192.000000">>%mundoname%.wrl
echo.531="192.000000">>%mundoname%.wrl
echo.530="%worldtile%">>%mundoname%.wrl
echo.522="224.000000">>%mundoname%.wrl
echo.521="192.000000">>%mundoname%.wrl
echo.520="%worldtile%">>%mundoname%.wrl
echo.512="112.000000">>%mundoname%.wrl
echo.511="240.000000">>%mundoname%.wrl
echo.510="%worldtile%">>%mundoname%.wrl
echo.502="112.000000">>%mundoname%.wrl
echo.501="288.000000">>%mundoname%.wrl
echo.500="%worldtile%">>%mundoname%.wrl
echo.492="112.000000">>%mundoname%.wrl
echo.491="272.000000">>%mundoname%.wrl
echo.490="%worldtile%">>%mundoname%.wrl
echo.482="112.000000">>%mundoname%.wrl
echo.481="256.000000">>%mundoname%.wrl
echo.480="%worldtile%">>%mundoname%.wrl
echo.472="112.000000">>%mundoname%.wrl
echo.471="224.000000">>%mundoname%.wrl
echo.470="%worldtile%">>%mundoname%.wrl
echo.462="112.000000">>%mundoname%.wrl
echo.461="208.000000">>%mundoname%.wrl
echo.460="%worldtile%">>%mundoname%.wrl
echo.452="128.000000">>%mundoname%.wrl
echo.451="272.000000">>%mundoname%.wrl
echo.450="%worldtile%">>%mundoname%.wrl
echo.442="128.000000">>%mundoname%.wrl
echo.441="272.000000">>%mundoname%.wrl
echo.440="obj_WE_mushhouseColocado">>%mundoname%.wrl
echo.432="128.000000">>%mundoname%.wrl
echo.431="256.000000">>%mundoname%.wrl
echo.430="%worldtile%">>%mundoname%.wrl
echo.422="128.000000">>%mundoname%.wrl
echo.421="288.000000">>%mundoname%.wrl
echo.420="%worldtile%">>%mundoname%.wrl
echo.412="128.000000">>%mundoname%.wrl
echo.411="224.000000">>%mundoname%.wrl
echo.410="%worldtile%">>%mundoname%.wrl
echo.402="144.000000">>%mundoname%.wrl
echo.401="288.000000">>%mundoname%.wrl
echo.400="%worldtile%">>%mundoname%.wrl
echo.392="144.000000">>%mundoname%.wrl
echo.391="272.000000">>%mundoname%.wrl
echo.390="%worldtile%">>%mundoname%.wrl
echo.382="144.000000">>%mundoname%.wrl
echo.381="256.000000">>%mundoname%.wrl
echo.380="%worldtile%">>%mundoname%.wrl
echo.372="144.000000">>%mundoname%.wrl
echo.371="240.000000">>%mundoname%.wrl
echo.370="%worldtile%">>%mundoname%.wrl
echo.362="144.000000">>%mundoname%.wrl
echo.361="224.000000">>%mundoname%.wrl
echo.360="%worldtile%">>%mundoname%.wrl
echo.352="144.000000">>%mundoname%.wrl
echo.351="208.000000">>%mundoname%.wrl
echo.350="%worldtile%">>%mundoname%.wrl
echo.342="160.000000">>%mundoname%.wrl
echo.341="288.000000">>%mundoname%.wrl
echo.340="%worldtile%">>%mundoname%.wrl
echo.332="160.000000">>%mundoname%.wrl
echo.331="224.000000">>%mundoname%.wrl
echo.330="%worldtile%">>%mundoname%.wrl
echo.322="160.000000">>%mundoname%.wrl
echo.321="272.000000">>%mundoname%.wrl
echo.320="%worldtile%">>%mundoname%.wrl
echo.312="160.000000">>%mundoname%.wrl
echo.311="256.000000">>%mundoname%.wrl
echo.310="%worldtile%">>%mundoname%.wrl
echo.302="192.000000">>%mundoname%.wrl
echo.301="272.000000">>%mundoname%.wrl
echo.300="obj_WE_mushhouseblueColocado">>%mundoname%.wrl
echo.292="176.000000">>%mundoname%.wrl
echo.291="288.000000">>%mundoname%.wrl
echo.290="%worldtile%">>%mundoname%.wrl
echo.282="192.000000">>%mundoname%.wrl
echo.281="288.000000">>%mundoname%.wrl
echo.280="%worldtile%">>%mundoname%.wrl
echo.272="208.000000">>%mundoname%.wrl
echo.271="288.000000">>%mundoname%.wrl
echo.270="%worldtile%">>%mundoname%.wrl
echo.262="224.000000">>%mundoname%.wrl
echo.261="288.000000">>%mundoname%.wrl
echo.260="%worldtile%">>%mundoname%.wrl
echo.252="240.000000">>%mundoname%.wrl
echo.251="288.000000">>%mundoname%.wrl
echo.250="%worldtile%">>%mundoname%.wrl
echo.242="240.000000">>%mundoname%.wrl
echo.241="272.000000">>%mundoname%.wrl
echo.240="%worldtile%">>%mundoname%.wrl
echo.232="224.000000">>%mundoname%.wrl
echo.231="272.000000">>%mundoname%.wrl
echo.230="%worldtile%">>%mundoname%.wrl
echo.222="208.000000">>%mundoname%.wrl
echo.221="272.000000">>%mundoname%.wrl
echo.220="%worldtile%">>%mundoname%.wrl
echo.212="192.000000">>%mundoname%.wrl
echo.211="272.000000">>%mundoname%.wrl
echo.210="%worldtile%">>%mundoname%.wrl
echo.202="176.000000">>%mundoname%.wrl
echo.201="272.000000">>%mundoname%.wrl
echo.200="%worldtile%">>%mundoname%.wrl
echo.192="176.000000">>%mundoname%.wrl
echo.191="256.000000">>%mundoname%.wrl
echo.190="%worldtile%">>%mundoname%.wrl
echo.182="192.000000">>%mundoname%.wrl
echo.181="256.000000">>%mundoname%.wrl
echo.180="%worldtile%">>%mundoname%.wrl
echo.172="240.000000">>%mundoname%.wrl
echo.171="256.000000">>%mundoname%.wrl
echo.170="%worldtile%">>%mundoname%.wrl
echo.162="208.000000">>%mundoname%.wrl
echo.161="240.000000">>%mundoname%.wrl
echo.160="%worldtile%">>%mundoname%.wrl
echo.152="240.000000">>%mundoname%.wrl
echo.151="224.000000">>%mundoname%.wrl
echo.150="%worldtile%">>%mundoname%.wrl
echo.142="224.000000">>%mundoname%.wrl
echo.141="256.000000">>%mundoname%.wrl
echo.140="%worldtile%">>%mundoname%.wrl
echo.132="176.000000">>%mundoname%.wrl
echo.131="240.000000">>%mundoname%.wrl
echo.130="%worldtile%">>%mundoname%.wrl
echo.122="224.000000">>%mundoname%.wrl
echo.121="224.000000">>%mundoname%.wrl
echo.120="%worldtile%">>%mundoname%.wrl
echo.112="240.000000">>%mundoname%.wrl
echo.111="208.000000">>%mundoname%.wrl
echo.110="%worldtile%">>%mundoname%.wrl
echo.102="208.000000">>%mundoname%.wrl
echo.101="224.000000">>%mundoname%.wrl
echo.100="%worldtile%">>%mundoname%.wrl
echo.92="192.000000">>%mundoname%.wrl
echo.91="224.000000">>%mundoname%.wrl
echo.90="%worldtile%">>%mundoname%.wrl
echo.82="208.000000">>%mundoname%.wrl
echo.81="208.000000">>%mundoname%.wrl
echo.80="%worldtile%">>%mundoname%.wrl
echo.72="176.000000">>%mundoname%.wrl
echo.71="208.000000">>%mundoname%.wrl
echo.70="%worldtile%">>%mundoname%.wrl
echo.62="176.000000">>%mundoname%.wrl
echo.61="224.000000">>%mundoname%.wrl
echo.60="%worldtile%">>%mundoname%.wrl
echo.52="176.000000">>%mundoname%.wrl
echo.51="192.000000">>%mundoname%.wrl
echo.50="%worldtile%">>%mundoname%.wrl
echo.42="176.000000">>%mundoname%.wrl
echo.41="160.000000">>%mundoname%.wrl
echo.40="%worldtile%">>%mundoname%.wrl
echo.32="176.000000">>%mundoname%.wrl
echo.31="128.000000">>%mundoname%.wrl
echo.30="%worldtile%">>%mundoname%.wrl
echo.22="208.000000">>%mundoname%.wrl
echo.21="256.000000">>%mundoname%.wrl
echo.20="%worldtile%">>%mundoname%.wrl
echo.12="240.000000">>%mundoname%.wrl
echo.11="240.000000">>%mundoname%.wrl
echo.10="%worldtile%">>%mundoname%.wrl
echo.02="240.000000">>%mundoname%.wrl
echo.01="192.000000">>%mundoname%.wrl
echo.00="%worldtile%">>%mundoname%.wrl
cls
echo.%msg015%
echo.%msg11%
echo. [██████████]99％
echo.[options]>>theend.lvl
echo.no_slide="off">>theend.lvl
echo.groundpound="off">>theend.lvl
echo.scroll_speed="-1">>theend.lvl
echo.light="off">>theend.lvl
echo.midari="off">>theend.lvl
echo.no_screen_limit="off">>theend.lvl
echo.no_pull="off">>theend.lvl
echo.waterlvl="off">>theend.lvl
echo.no_spinjump="off">>theend.lvl
echo.no_grab="off">>theend.lvl
echo.no_reserve="off">>theend.lvl
echo.health="off">>theend.lvl
echo.room_y="432">>theend.lvl
echo.room_x="8000">>theend.lvl
echo.angrysun="off">>theend.lvl
echo.niebla="off">>theend.lvl
echo.snowGen="off">>theend.lvl
echo.cheepGen="off">>theend.lvl
echo.walljump="off">>theend.lvl
echo.mapas="1">>theend.lvl
echo.tiempo_count="300">>theend.lvl
echo.tiempo="off">>theend.lvl
echo.flagpole_y="224">>theend.lvl
echo.flagpole_x="3488">>theend.lvl
echo.incastle_y="368">>theend.lvl
echo.incastle_x="3616">>theend.lvl
echo.mario_y="352">>theend.lvl
echo.mario_x="40">>theend.lvl
echo.storm="off">>theend.lvl
echo.modo="1">>theend.lvl
echo.musica_le="170">>theend.lvl
echo.musica="61">>theend.lvl
echo.bg="8">>theend.lvl
echo.background="8">>theend.lvl
echo.[colocado3]>>theend.lvl
echo.203="%genmsg01%">>theend.lvl
echo.202="264">>theend.lvl
echo.201="16">>theend.lvl
echo.200="obj_LE_text_Colocado">>theend.lvl
echo.193="%genmsg02%">>theend.lvl
echo.192="280">>theend.lvl
echo.191="16">>theend.lvl
echo.190="obj_LE_text_Colocado">>theend.lvl
echo.183="%genmsg03%">>theend.lvl
echo.182="296">>theend.lvl
echo.181="16">>theend.lvl
echo.180="obj_LE_text_Colocado">>theend.lvl
echo.173="%genmsg04%">>theend.lvl
echo.172="304">>theend.lvl
echo.171="992">>theend.lvl
echo.170="obj_LE_text_Colocado">>theend.lvl
echo.163="%level_01%">>theend.lvl
echo.162="248">>theend.lvl
echo.161="296">>theend.lvl
echo.160="obj_LE_text_Colocado">>theend.lvl
echo.153="%level_02%">>theend.lvl
echo.152="264">>theend.lvl
echo.151="296">>theend.lvl
echo.150="obj_LE_text_Colocado">>theend.lvl
echo.143="%level_03%">>theend.lvl
echo.142="280">>theend.lvl
echo.141="296">>theend.lvl
echo.140="obj_LE_text_Colocado">>theend.lvl
echo.133="%level_04%">>theend.lvl
echo.132="296">>theend.lvl
echo.131="296">>theend.lvl
echo.130="obj_LE_text_Colocado">>theend.lvl
echo.123="%level_05%">>theend.lvl
echo.122="312">>theend.lvl
echo.121="296">>theend.lvl
echo.120="obj_LE_text_Colocado">>theend.lvl
echo.113="%level_06%">>theend.lvl
echo.112="248">>theend.lvl
echo.111="488">>theend.lvl
echo.110="obj_LE_text_Colocado">>theend.lvl
echo.103="%level_08%">>theend.lvl
echo.102="280">>theend.lvl
echo.101="488">>theend.lvl
echo.100="obj_LE_text_Colocado">>theend.lvl
echo.93="%level_07%">>theend.lvl
echo.92="264">>theend.lvl
echo.91="488">>theend.lvl
echo.90="obj_LE_text_Colocado">>theend.lvl
echo.83="%level_09%">>theend.lvl
echo.82="296">>theend.lvl
echo.81="488">>theend.lvl
echo.80="obj_LE_text_Colocado">>theend.lvl
echo.73="%genmsg05%">>theend.lvl
echo.72="312">>theend.lvl
echo.71="16">>theend.lvl
echo.70="obj_LE_text_Colocado">>theend.lvl
echo.63="%level_10%">>theend.lvl
echo.62="312">>theend.lvl
echo.61="488">>theend.lvl
echo.60="obj_LE_text_Colocado">>theend.lvl
echo.53="%level_11%">>theend.lvl
echo.52="248">>theend.lvl
echo.51="696">>theend.lvl
echo.50="obj_LE_text_Colocado">>theend.lvl
echo.43="%level_12%">>theend.lvl
echo.42="264">>theend.lvl
echo.41="696">>theend.lvl
echo.40="obj_LE_text_Colocado">>theend.lvl
echo.33="%level_13%">>theend.lvl
echo.32="280">>theend.lvl
echo.31="696">>theend.lvl
echo.30="obj_LE_text_Colocado">>theend.lvl
echo.23="%level_14%">>theend.lvl
echo.22="296">>theend.lvl
echo.21="696">>theend.lvl
echo.20="obj_LE_text_Colocado">>theend.lvl
echo.13="%level_15%">>theend.lvl
echo.12="312">>theend.lvl
echo.11="696">>theend.lvl
echo.10="obj_LE_text_Colocado">>theend.lvl
echo.03="%level_16%">>theend.lvl
echo.02="328">>theend.lvl
echo.01="696">>theend.lvl
echo.00="obj_LE_text_Colocado">>theend.lvl
echo.[colocado2]>>theend.lvl
echo.162="368">>theend.lvl
echo.161="896">>theend.lvl
echo.160="obj_LE_vallaColocado">>theend.lvl
echo.152="368">>theend.lvl
echo.151="912">>theend.lvl
echo.150="obj_LE_vallaColocado">>theend.lvl
echo.142="352">>theend.lvl
echo.141="976">>theend.lvl
echo.140="obj_LE_arbol3_Colocado">>theend.lvl
echo.132="368">>theend.lvl
echo.131="976">>theend.lvl
echo.130="obj_LE_arbol3_Colocado">>theend.lvl
echo.122="352">>theend.lvl
echo.121="1024">>theend.lvl
echo.120="obj_LE_arbol1_Colocado">>theend.lvl
echo.112="368">>theend.lvl
echo.111="1024">>theend.lvl
echo.110="obj_LE_arbol1_Colocado">>theend.lvl
echo.102="368">>theend.lvl
echo.101="880">>theend.lvl
echo.100="obj_LE_vallaColocado">>theend.lvl
echo.92="368">>theend.lvl
echo.91="864">>theend.lvl
echo.90="obj_LE_vallaColocado">>theend.lvl
echo.82="368">>theend.lvl
echo.81="80">>theend.lvl
echo.80="obj_LE_arbol1_Colocado">>theend.lvl
echo.72="352">>theend.lvl
echo.71="80">>theend.lvl
echo.70="obj_LE_arbol1_Colocado">>theend.lvl
echo.62="352">>theend.lvl
echo.61="224">>theend.lvl
echo.60="obj_LE_cactus_Colocado">>theend.lvl
echo.52="368">>theend.lvl
echo.51="224">>theend.lvl
echo.50="obj_LE_cactus_Colocado">>theend.lvl
echo.42="336">>theend.lvl
echo.41="304">>theend.lvl
echo.40="obj_LE_cactus2_Colocado">>theend.lvl
echo.32="352">>theend.lvl
echo.31="304">>theend.lvl
echo.30="obj_LE_cactus2_Colocado">>theend.lvl
echo.22="368">>theend.lvl
echo.21="304">>theend.lvl
echo.20="obj_LE_cactus2_Colocado">>theend.lvl
echo.12="352">>theend.lvl
echo.11="496">>theend.lvl
echo.10="obj_LE_arbol3_Colocado">>theend.lvl
echo.02="368">>theend.lvl
echo.01="496">>theend.lvl
echo.00="obj_LE_arbol3_Colocado">>theend.lvl
echo.[colocado]>>theend.lvl
echo.3332="384">>theend.lvl
echo.3331="896">>theend.lvl
echo.3330="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3322="400">>theend.lvl
echo.3321="896">>theend.lvl
echo.3320="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3312="416">>theend.lvl
echo.3311="896">>theend.lvl
echo.3310="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3302="432">>theend.lvl
echo.3301="896">>theend.lvl
echo.3300="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3292="384">>theend.lvl
echo.3291="912">>theend.lvl
echo.3290="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3282="400">>theend.lvl
echo.3281="912">>theend.lvl
echo.3280="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3272="416">>theend.lvl
echo.3271="912">>theend.lvl
echo.3270="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3262="432">>theend.lvl
echo.3261="912">>theend.lvl
echo.3260="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3252="384">>theend.lvl
echo.3251="928">>theend.lvl
echo.3250="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3242="400">>theend.lvl
echo.3241="928">>theend.lvl
echo.3240="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3232="416">>theend.lvl
echo.3231="928">>theend.lvl
echo.3230="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3222="432">>theend.lvl
echo.3221="928">>theend.lvl
echo.3220="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3212="352">>theend.lvl
echo.3211="944">>theend.lvl
echo.3210="obj_LE_arbol2_Colocado">>theend.lvl
echo.3202="368">>theend.lvl
echo.3201="944">>theend.lvl
echo.3200="obj_LE_arbol2_Colocado">>theend.lvl
echo.3192="384">>theend.lvl
echo.3191="944">>theend.lvl
echo.3190="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3182="400">>theend.lvl
echo.3181="944">>theend.lvl
echo.3180="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3172="416">>theend.lvl
echo.3171="944">>theend.lvl
echo.3170="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3162="432">>theend.lvl
echo.3161="944">>theend.lvl
echo.3160="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3152="384">>theend.lvl
echo.3151="960">>theend.lvl
echo.3150="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3142="400">>theend.lvl
echo.3141="960">>theend.lvl
echo.3140="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3132="416">>theend.lvl
echo.3131="960">>theend.lvl
echo.3130="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3122="432">>theend.lvl
echo.3121="960">>theend.lvl
echo.3120="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3112="384">>theend.lvl
echo.3111="976">>theend.lvl
echo.3110="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3102="400">>theend.lvl
echo.3101="976">>theend.lvl
echo.3100="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3092="416">>theend.lvl
echo.3091="976">>theend.lvl
echo.3090="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3082="432">>theend.lvl
echo.3081="976">>theend.lvl
echo.3080="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3072="384">>theend.lvl
echo.3071="992">>theend.lvl
echo.3070="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3062="400">>theend.lvl
echo.3061="992">>theend.lvl
echo.3060="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3052="416">>theend.lvl
echo.3051="992">>theend.lvl
echo.3050="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3042="432">>theend.lvl
echo.3041="992">>theend.lvl
echo.3040="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3032="384">>theend.lvl
echo.3031="1008">>theend.lvl
echo.3030="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3022="400">>theend.lvl
echo.3021="1008">>theend.lvl
echo.3020="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3012="416">>theend.lvl
echo.3011="1008">>theend.lvl
echo.3010="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.3002="432">>theend.lvl
echo.3001="1008">>theend.lvl
echo.3000="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2992="384">>theend.lvl
echo.2991="1024">>theend.lvl
echo.2990="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2982="400">>theend.lvl
echo.2981="1024">>theend.lvl
echo.2980="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2972="416">>theend.lvl
echo.2971="1024">>theend.lvl
echo.2970="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2962="432">>theend.lvl
echo.2961="1024">>theend.lvl
echo.2960="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2952="384">>theend.lvl
echo.2951="1040">>theend.lvl
echo.2950="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2942="400">>theend.lvl
echo.2941="1040">>theend.lvl
echo.2940="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2932="416">>theend.lvl
echo.2931="1040">>theend.lvl
echo.2930="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2922="432">>theend.lvl
echo.2921="1040">>theend.lvl
echo.2920="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2912="384">>theend.lvl
echo.2911="1056">>theend.lvl
echo.2910="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2902="400">>theend.lvl
echo.2901="1056">>theend.lvl
echo.2900="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2892="416">>theend.lvl
echo.2891="1056">>theend.lvl
echo.2890="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2882="432">>theend.lvl
echo.2881="1056">>theend.lvl
echo.2880="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2872="384">>theend.lvl
echo.2871="1072">>theend.lvl
echo.2870="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2862="400">>theend.lvl
echo.2861="1072">>theend.lvl
echo.2860="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2852="416">>theend.lvl
echo.2851="1072">>theend.lvl
echo.2850="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2842="432">>theend.lvl
echo.2841="1072">>theend.lvl
echo.2840="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2832="384">>theend.lvl
echo.2831="1088">>theend.lvl
echo.2830="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2822="400">>theend.lvl
echo.2821="1088">>theend.lvl
echo.2820="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2812="416">>theend.lvl
echo.2811="1088">>theend.lvl
echo.2810="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2802="432">>theend.lvl
echo.2801="1088">>theend.lvl
echo.2800="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2792="352">>theend.lvl
echo.2791="1000">>theend.lvl
echo.2790="obj_LE_princessTalkColocado">>theend.lvl
echo.2782="240">>theend.lvl
echo.2781="1056">>theend.lvl
echo.2780="obj_LE_goalgate_Colocado">>theend.lvl
echo.2772="352">>theend.lvl
echo.2771="892">>theend.lvl
echo.2770="obj_LE_rosalinaColocado">>theend.lvl
echo.2762="384">>theend.lvl
echo.2761="880">>theend.lvl
echo.2760="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2752="400">>theend.lvl
echo.2751="880">>theend.lvl
echo.2750="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2742="416">>theend.lvl
echo.2741="880">>theend.lvl
echo.2740="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2732="432">>theend.lvl
echo.2731="880">>theend.lvl
echo.2730="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2722="384">>theend.lvl
echo.2721="864">>theend.lvl
echo.2720="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2712="400">>theend.lvl
echo.2711="864">>theend.lvl
echo.2710="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2702="416">>theend.lvl
echo.2701="864">>theend.lvl
echo.2700="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2692="432">>theend.lvl
echo.2691="864">>theend.lvl
echo.2690="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2682="384">>theend.lvl
echo.2681="848">>theend.lvl
echo.2680="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2672="400">>theend.lvl
echo.2671="848">>theend.lvl
echo.2670="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2662="416">>theend.lvl
echo.2661="848">>theend.lvl
echo.2660="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2652="432">>theend.lvl
echo.2651="848">>theend.lvl
echo.2650="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2642="352">>theend.lvl
echo.2641="848">>theend.lvl
echo.2640="obj_LE_daisyTalkColocado">>theend.lvl
echo.2632="384">>theend.lvl
echo.2631="832">>theend.lvl
echo.2630="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2622="400">>theend.lvl
echo.2621="832">>theend.lvl
echo.2620="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2612="416">>theend.lvl
echo.2611="832">>theend.lvl
echo.2610="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2602="432">>theend.lvl
echo.2601="832">>theend.lvl
echo.2600="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2592="336">>theend.lvl
echo.2591="800">>theend.lvl
echo.2590="obj_LE_palmeraColocado">>theend.lvl
echo.2582="384">>theend.lvl
echo.2581="816">>theend.lvl
echo.2580="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2572="400">>theend.lvl
echo.2571="816">>theend.lvl
echo.2570="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2562="416">>theend.lvl
echo.2561="816">>theend.lvl
echo.2560="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2552="432">>theend.lvl
echo.2551="816">>theend.lvl
echo.2550="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2542="384">>theend.lvl
echo.2541="800">>theend.lvl
echo.2540="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2532="400">>theend.lvl
echo.2531="800">>theend.lvl
echo.2530="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2522="416">>theend.lvl
echo.2521="800">>theend.lvl
echo.2520="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2512="432">>theend.lvl
echo.2511="800">>theend.lvl
echo.2510="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2502="384">>theend.lvl
echo.2501="784">>theend.lvl
echo.2500="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2492="400">>theend.lvl
echo.2491="784">>theend.lvl
echo.2490="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2482="416">>theend.lvl
echo.2481="784">>theend.lvl
echo.2480="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2472="432">>theend.lvl
echo.2471="784">>theend.lvl
echo.2470="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2462="352">>theend.lvl
echo.2461="792">>theend.lvl
echo.2460="obj_LE_waluigiColocado">>theend.lvl
echo.2452="336">>theend.lvl
echo.2451="704">>theend.lvl
echo.2450="obj_LE_montainColocado">>theend.lvl
echo.2442="384">>theend.lvl
echo.2441="768">>theend.lvl
echo.2440="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2432="400">>theend.lvl
echo.2431="768">>theend.lvl
echo.2430="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2422="416">>theend.lvl
echo.2421="768">>theend.lvl
echo.2420="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2412="432">>theend.lvl
echo.2411="768">>theend.lvl
echo.2410="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2402="384">>theend.lvl
echo.2401="1104">>theend.lvl
echo.2400="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2392="400">>theend.lvl
echo.2391="1104">>theend.lvl
echo.2390="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2382="416">>theend.lvl
echo.2381="1104">>theend.lvl
echo.2380="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2372="432">>theend.lvl
echo.2371="1104">>theend.lvl
echo.2370="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2362="384">>theend.lvl
echo.2361="1120">>theend.lvl
echo.2360="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2352="400">>theend.lvl
echo.2351="1120">>theend.lvl
echo.2350="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2342="416">>theend.lvl
echo.2341="1120">>theend.lvl
echo.2340="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2332="432">>theend.lvl
echo.2331="1120">>theend.lvl
echo.2330="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2322="384">>theend.lvl
echo.2321="1136">>theend.lvl
echo.2320="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2312="400">>theend.lvl
echo.2311="1136">>theend.lvl
echo.2310="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2302="416">>theend.lvl
echo.2301="1136">>theend.lvl
echo.2300="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2292="432">>theend.lvl
echo.2291="1136">>theend.lvl
echo.2290="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2282="384">>theend.lvl
echo.2281="1152">>theend.lvl
echo.2280="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2272="400">>theend.lvl
echo.2271="1152">>theend.lvl
echo.2270="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2262="416">>theend.lvl
echo.2261="1152">>theend.lvl
echo.2260="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2252="432">>theend.lvl
echo.2251="1152">>theend.lvl
echo.2250="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2242="384">>theend.lvl
echo.2241="1168">>theend.lvl
echo.2240="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2232="400">>theend.lvl
echo.2231="1168">>theend.lvl
echo.2230="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2222="416">>theend.lvl
echo.2221="1168">>theend.lvl
echo.2220="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2212="432">>theend.lvl
echo.2211="1168">>theend.lvl
echo.2210="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2202="384">>theend.lvl
echo.2201="1184">>theend.lvl
echo.2200="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2192="400">>theend.lvl
echo.2191="1184">>theend.lvl
echo.2190="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2182="416">>theend.lvl
echo.2181="1184">>theend.lvl
echo.2180="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2172="432">>theend.lvl
echo.2171="1184">>theend.lvl
echo.2170="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2162="384">>theend.lvl
echo.2161="1200">>theend.lvl
echo.2160="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2152="400">>theend.lvl
echo.2151="1200">>theend.lvl
echo.2150="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2142="416">>theend.lvl
echo.2141="1200">>theend.lvl
echo.2140="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2132="432">>theend.lvl
echo.2131="1200">>theend.lvl
echo.2130="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2122="384">>theend.lvl
echo.2121="752">>theend.lvl
echo.2120="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2112="400">>theend.lvl
echo.2111="752">>theend.lvl
echo.2110="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2102="416">>theend.lvl
echo.2101="752">>theend.lvl
echo.2100="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2092="432">>theend.lvl
echo.2091="752">>theend.lvl
echo.2090="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2082="384">>theend.lvl
echo.2081="0">>theend.lvl
echo.2080="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2072="400">>theend.lvl
echo.2071="0">>theend.lvl
echo.2070="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2062="416">>theend.lvl
echo.2061="0">>theend.lvl
echo.2060="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2052="432">>theend.lvl
echo.2051="0">>theend.lvl
echo.2050="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2042="384">>theend.lvl
echo.2041="16">>theend.lvl
echo.2040="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2032="400">>theend.lvl
echo.2031="16">>theend.lvl
echo.2030="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2022="416">>theend.lvl
echo.2021="16">>theend.lvl
echo.2020="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2012="432">>theend.lvl
echo.2011="16">>theend.lvl
echo.2010="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.2002="432">>theend.lvl
echo.2001="80">>theend.lvl
echo.2000="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1992="432">>theend.lvl
echo.1991="64">>theend.lvl
echo.1990="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1982="432">>theend.lvl
echo.1981="48">>theend.lvl
echo.1980="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1972="432">>theend.lvl
echo.1971="32">>theend.lvl
echo.1970="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1962="416">>theend.lvl
echo.1961="80">>theend.lvl
echo.1960="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1952="416">>theend.lvl
echo.1951="64">>theend.lvl
echo.1950="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1942="416">>theend.lvl
echo.1941="48">>theend.lvl
echo.1940="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1932="384">>theend.lvl
echo.1931="32">>theend.lvl
echo.1930="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1922="400">>theend.lvl
echo.1921="32">>theend.lvl
echo.1920="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1912="416">>theend.lvl
echo.1911="32">>theend.lvl
echo.1910="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1902="400">>theend.lvl
echo.1901="80">>theend.lvl
echo.1900="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1892="400">>theend.lvl
echo.1891="64">>theend.lvl
echo.1890="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1882="400">>theend.lvl
echo.1881="48">>theend.lvl
echo.1880="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1872="384">>theend.lvl
echo.1871="48">>theend.lvl
echo.1870="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1862="384">>theend.lvl
echo.1861="80">>theend.lvl
echo.1860="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1852="384">>theend.lvl
echo.1851="64">>theend.lvl
echo.1850="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1842="384">>theend.lvl
echo.1841="96">>theend.lvl
echo.1840="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1832="400">>theend.lvl
echo.1831="96">>theend.lvl
echo.1830="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1822="416">>theend.lvl
echo.1821="96">>theend.lvl
echo.1820="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1812="432">>theend.lvl
echo.1811="96">>theend.lvl
echo.1810="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1802="352">>theend.lvl
echo.1801="112">>theend.lvl
echo.1800="obj_LE_arbol2_Colocado">>theend.lvl
echo.1792="368">>theend.lvl
echo.1791="112">>theend.lvl
echo.1790="obj_LE_arbol2_Colocado">>theend.lvl
echo.1782="384">>theend.lvl
echo.1781="112">>theend.lvl
echo.1780="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1772="400">>theend.lvl
echo.1771="112">>theend.lvl
echo.1770="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1762="416">>theend.lvl
echo.1761="112">>theend.lvl
echo.1760="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1752="432">>theend.lvl
echo.1751="112">>theend.lvl
echo.1750="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1742="384">>theend.lvl
echo.1741="128">>theend.lvl
echo.1740="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1732="400">>theend.lvl
echo.1731="128">>theend.lvl
echo.1730="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1722="416">>theend.lvl
echo.1721="128">>theend.lvl
echo.1720="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1712="432">>theend.lvl
echo.1711="128">>theend.lvl
echo.1710="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1702="384">>theend.lvl
echo.1701="144">>theend.lvl
echo.1700="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1692="400">>theend.lvl
echo.1691="144">>theend.lvl
echo.1690="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1682="416">>theend.lvl
echo.1681="144">>theend.lvl
echo.1680="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1672="432">>theend.lvl
echo.1671="144">>theend.lvl
echo.1670="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1662="368">>theend.lvl
echo.1661="160">>theend.lvl
echo.1660="obj_LE_arbol2_Colocado">>theend.lvl
echo.1652="384">>theend.lvl
echo.1651="160">>theend.lvl
echo.1650="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1642="400">>theend.lvl
echo.1641="160">>theend.lvl
echo.1640="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1632="416">>theend.lvl
echo.1631="160">>theend.lvl
echo.1630="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1622="432">>theend.lvl
echo.1621="160">>theend.lvl
echo.1620="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1612="384">>theend.lvl
echo.1611="176">>theend.lvl
echo.1610="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1602="400">>theend.lvl
echo.1601="176">>theend.lvl
echo.1600="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1592="416">>theend.lvl
echo.1591="176">>theend.lvl
echo.1590="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1582="432">>theend.lvl
echo.1581="176">>theend.lvl
echo.1580="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1572="384">>theend.lvl
echo.1571="192">>theend.lvl
echo.1570="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1562="400">>theend.lvl
echo.1561="192">>theend.lvl
echo.1560="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1552="416">>theend.lvl
echo.1551="192">>theend.lvl
echo.1550="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1542="432">>theend.lvl
echo.1541="192">>theend.lvl
echo.1540="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1532="384">>theend.lvl
echo.1531="208">>theend.lvl
echo.1530="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1522="400">>theend.lvl
echo.1521="208">>theend.lvl
echo.1520="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1512="416">>theend.lvl
echo.1511="208">>theend.lvl
echo.1510="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1502="432">>theend.lvl
echo.1501="208">>theend.lvl
echo.1500="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1492="384">>theend.lvl
echo.1491="224">>theend.lvl
echo.1490="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1482="400">>theend.lvl
echo.1481="224">>theend.lvl
echo.1480="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1472="416">>theend.lvl
echo.1471="224">>theend.lvl
echo.1470="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1462="432">>theend.lvl
echo.1461="224">>theend.lvl
echo.1460="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1452="384">>theend.lvl
echo.1451="240">>theend.lvl
echo.1450="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1442="400">>theend.lvl
echo.1441="240">>theend.lvl
echo.1440="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1432="416">>theend.lvl
echo.1431="240">>theend.lvl
echo.1430="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1422="432">>theend.lvl
echo.1421="240">>theend.lvl
echo.1420="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1412="352">>theend.lvl
echo.1411="256">>theend.lvl
echo.1410="obj_LE_luigiTalkColocado">>theend.lvl
echo.1402="384">>theend.lvl
echo.1401="256">>theend.lvl
echo.1400="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1392="400">>theend.lvl
echo.1391="256">>theend.lvl
echo.1390="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1382="416">>theend.lvl
echo.1381="256">>theend.lvl
echo.1380="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1372="432">>theend.lvl
echo.1371="256">>theend.lvl
echo.1370="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1362="384">>theend.lvl
echo.1361="272">>theend.lvl
echo.1360="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1352="400">>theend.lvl
echo.1351="272">>theend.lvl
echo.1350="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1342="416">>theend.lvl
echo.1341="272">>theend.lvl
echo.1340="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1332="432">>theend.lvl
echo.1331="272">>theend.lvl
echo.1330="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1322="384">>theend.lvl
echo.1321="288">>theend.lvl
echo.1320="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1312="400">>theend.lvl
echo.1311="288">>theend.lvl
echo.1310="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1302="416">>theend.lvl
echo.1301="288">>theend.lvl
echo.1300="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1292="432">>theend.lvl
echo.1291="288">>theend.lvl
echo.1290="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1282="384">>theend.lvl
echo.1281="304">>theend.lvl
echo.1280="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1272="400">>theend.lvl
echo.1271="304">>theend.lvl
echo.1270="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1262="416">>theend.lvl
echo.1261="304">>theend.lvl
echo.1260="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1252="432">>theend.lvl
echo.1251="304">>theend.lvl
echo.1250="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1242="384">>theend.lvl
echo.1241="320">>theend.lvl
echo.1240="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1232="400">>theend.lvl
echo.1231="320">>theend.lvl
echo.1230="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1222="416">>theend.lvl
echo.1221="320">>theend.lvl
echo.1220="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1212="432">>theend.lvl
echo.1211="320">>theend.lvl
echo.1210="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1202="352">>theend.lvl
echo.1201="336">>theend.lvl
echo.1200="obj_LE_toadTalkColocado">>theend.lvl
echo.1192="384">>theend.lvl
echo.1191="336">>theend.lvl
echo.1190="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1182="400">>theend.lvl
echo.1181="336">>theend.lvl
echo.1180="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1172="416">>theend.lvl
echo.1171="336">>theend.lvl
echo.1170="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1162="432">>theend.lvl
echo.1161="336">>theend.lvl
echo.1160="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1152="384">>theend.lvl
echo.1151="352">>theend.lvl
echo.1150="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1142="400">>theend.lvl
echo.1141="352">>theend.lvl
echo.1140="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1132="416">>theend.lvl
echo.1131="352">>theend.lvl
echo.1130="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1122="432">>theend.lvl
echo.1121="352">>theend.lvl
echo.1120="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1112="384">>theend.lvl
echo.1111="368">>theend.lvl
echo.1110="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1102="400">>theend.lvl
echo.1101="368">>theend.lvl
echo.1100="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1092="416">>theend.lvl
echo.1091="368">>theend.lvl
echo.1090="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1082="432">>theend.lvl
echo.1081="368">>theend.lvl
echo.1080="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1072="368">>theend.lvl
echo.1071="368">>theend.lvl
echo.1070="obj_LE_arbustoLE_Colocado">>theend.lvl
echo.1062="384">>theend.lvl
echo.1061="384">>theend.lvl
echo.1060="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1052="400">>theend.lvl
echo.1051="384">>theend.lvl
echo.1050="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1042="416">>theend.lvl
echo.1041="384">>theend.lvl
echo.1040="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1032="432">>theend.lvl
echo.1031="384">>theend.lvl
echo.1030="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1022="368">>theend.lvl
echo.1021="384">>theend.lvl
echo.1020="obj_LE_arbustoLE_Colocado">>theend.lvl
echo.1012="384">>theend.lvl
echo.1011="400">>theend.lvl
echo.1010="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.1002="400">>theend.lvl
echo.1001="400">>theend.lvl
echo.1000="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.992="416">>theend.lvl
echo.991="400">>theend.lvl
echo.990="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.982="432">>theend.lvl
echo.981="400">>theend.lvl
echo.980="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.972="384">>theend.lvl
echo.971="416">>theend.lvl
echo.970="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.962="400">>theend.lvl
echo.961="416">>theend.lvl
echo.960="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.952="416">>theend.lvl
echo.951="416">>theend.lvl
echo.950="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.942="432">>theend.lvl
echo.941="416">>theend.lvl
echo.940="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.932="352">>theend.lvl
echo.931="424">>theend.lvl
echo.930="obj_LE_toadsworthColocado">>theend.lvl
echo.922="384">>theend.lvl
echo.921="432">>theend.lvl
echo.920="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.912="400">>theend.lvl
echo.911="432">>theend.lvl
echo.910="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.902="416">>theend.lvl
echo.901="432">>theend.lvl
echo.900="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.892="432">>theend.lvl
echo.891="432">>theend.lvl
echo.890="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.882="336">>theend.lvl
echo.881="448">>theend.lvl
echo.880="obj_LE_arbol2_Colocado">>theend.lvl
echo.872="352">>theend.lvl
echo.871="448">>theend.lvl
echo.870="obj_LE_arbol2_Colocado">>theend.lvl
echo.862="368">>theend.lvl
echo.861="448">>theend.lvl
echo.860="obj_LE_arbol2_Colocado">>theend.lvl
echo.852="384">>theend.lvl
echo.851="448">>theend.lvl
echo.850="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.842="400">>theend.lvl
echo.841="448">>theend.lvl
echo.840="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.832="416">>theend.lvl
echo.831="448">>theend.lvl
echo.830="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.822="432">>theend.lvl
echo.821="448">>theend.lvl
echo.820="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.812="384">>theend.lvl
echo.811="464">>theend.lvl
echo.810="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.802="400">>theend.lvl
echo.801="464">>theend.lvl
echo.800="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.792="416">>theend.lvl
echo.791="464">>theend.lvl
echo.790="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.782="432">>theend.lvl
echo.781="464">>theend.lvl
echo.780="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.772="352">>theend.lvl
echo.771="480">>theend.lvl
echo.770="obj_LE_EGaddColocado">>theend.lvl
echo.762="384">>theend.lvl
echo.761="480">>theend.lvl
echo.760="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.752="400">>theend.lvl
echo.751="480">>theend.lvl
echo.750="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.742="416">>theend.lvl
echo.741="480">>theend.lvl
echo.740="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.732="432">>theend.lvl
echo.731="480">>theend.lvl
echo.730="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.722="384">>theend.lvl
echo.721="496">>theend.lvl
echo.720="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.712="400">>theend.lvl
echo.711="496">>theend.lvl
echo.710="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.702="416">>theend.lvl
echo.701="496">>theend.lvl
echo.700="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.692="432">>theend.lvl
echo.691="496">>theend.lvl
echo.690="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.682="384">>theend.lvl
echo.681="512">>theend.lvl
echo.680="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.672="400">>theend.lvl
echo.671="512">>theend.lvl
echo.670="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.662="416">>theend.lvl
echo.661="512">>theend.lvl
echo.660="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.652="432">>theend.lvl
echo.651="512">>theend.lvl
echo.650="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.642="384">>theend.lvl
echo.641="528">>theend.lvl
echo.640="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.632="400">>theend.lvl
echo.631="528">>theend.lvl
echo.630="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.622="416">>theend.lvl
echo.621="528">>theend.lvl
echo.620="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.612="432">>theend.lvl
echo.611="528">>theend.lvl
echo.610="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.602="352">>theend.lvl
echo.601="544">>theend.lvl
echo.600="obj_LE_arbol2_Colocado">>theend.lvl
echo.592="368">>theend.lvl
echo.591="544">>theend.lvl
echo.590="obj_LE_arbol2_Colocado">>theend.lvl
echo.582="384">>theend.lvl
echo.581="544">>theend.lvl
echo.580="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.572="400">>theend.lvl
echo.571="544">>theend.lvl
echo.570="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.562="416">>theend.lvl
echo.561="544">>theend.lvl
echo.560="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.552="432">>theend.lvl
echo.551="544">>theend.lvl
echo.550="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.542="384">>theend.lvl
echo.541="560">>theend.lvl
echo.540="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.532="400">>theend.lvl
echo.531="560">>theend.lvl
echo.530="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.522="416">>theend.lvl
echo.521="560">>theend.lvl
echo.520="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.512="432">>theend.lvl
echo.511="560">>theend.lvl
echo.510="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.502="352">>theend.lvl
echo.501="576">>theend.lvl
echo.500="obj_LE_toadsworthColocado">>theend.lvl
echo.492="384">>theend.lvl
echo.491="576">>theend.lvl
echo.490="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.482="400">>theend.lvl
echo.481="576">>theend.lvl
echo.480="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.472="416">>theend.lvl
echo.471="576">>theend.lvl
echo.470="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.462="432">>theend.lvl
echo.461="576">>theend.lvl
echo.460="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.452="384">>theend.lvl
echo.451="592">>theend.lvl
echo.450="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.442="400">>theend.lvl
echo.441="592">>theend.lvl
echo.440="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.432="416">>theend.lvl
echo.431="592">>theend.lvl
echo.430="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.422="432">>theend.lvl
echo.421="592">>theend.lvl
echo.420="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.412="336">>theend.lvl
echo.411="592">>theend.lvl
echo.410="obj_LE_arbolLE_Colocado">>theend.lvl
echo.402="384">>theend.lvl
echo.401="608">>theend.lvl
echo.400="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.392="400">>theend.lvl
echo.391="608">>theend.lvl
echo.390="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.382="416">>theend.lvl
echo.381="608">>theend.lvl
echo.380="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.372="432">>theend.lvl
echo.371="608">>theend.lvl
echo.370="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.362="384">>theend.lvl
echo.361="624">>theend.lvl
echo.360="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.352="400">>theend.lvl
echo.351="624">>theend.lvl
echo.350="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.342="416">>theend.lvl
echo.341="624">>theend.lvl
echo.340="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.332="432">>theend.lvl
echo.331="624">>theend.lvl
echo.330="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.322="432">>theend.lvl
echo.321="1248">>theend.lvl
echo.320="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.312="432">>theend.lvl
echo.311="1232">>theend.lvl
echo.310="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.302="384">>theend.lvl
echo.301="640">>theend.lvl
echo.300="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.292="400">>theend.lvl
echo.291="640">>theend.lvl
echo.290="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.282="416">>theend.lvl
echo.281="640">>theend.lvl
echo.280="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.272="432">>theend.lvl
echo.271="640">>theend.lvl
echo.270="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.262="368">>theend.lvl
echo.261="624">>theend.lvl
echo.260="obj_LE_animgrassColocado">>theend.lvl
echo.252="384">>theend.lvl
echo.251="656">>theend.lvl
echo.250="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.242="400">>theend.lvl
echo.241="656">>theend.lvl
echo.240="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.232="416">>theend.lvl
echo.231="656">>theend.lvl
echo.230="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.222="432">>theend.lvl
echo.221="656">>theend.lvl
echo.220="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.212="384">>theend.lvl
echo.211="672">>theend.lvl
echo.210="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.202="400">>theend.lvl
echo.201="672">>theend.lvl
echo.200="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.192="416">>theend.lvl
echo.191="672">>theend.lvl
echo.190="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.182="432">>theend.lvl
echo.181="672">>theend.lvl
echo.180="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.172="352">>theend.lvl
echo.171="688">>theend.lvl
echo.170="obj_LE_warioColocado">>theend.lvl
echo.162="384">>theend.lvl
echo.161="688">>theend.lvl
echo.160="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.152="400">>theend.lvl
echo.151="688">>theend.lvl
echo.150="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.142="416">>theend.lvl
echo.141="688">>theend.lvl
echo.140="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.132="432">>theend.lvl
echo.131="688">>theend.lvl
echo.130="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.122="384">>theend.lvl
echo.121="704">>theend.lvl
echo.120="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.112="400">>theend.lvl
echo.111="704">>theend.lvl
echo.110="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.102="416">>theend.lvl
echo.101="704">>theend.lvl
echo.100="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.92="432">>theend.lvl
echo.91="704">>theend.lvl
echo.90="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.82="384">>theend.lvl
echo.81="720">>theend.lvl
echo.80="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.72="400">>theend.lvl
echo.71="720">>theend.lvl
echo.70="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.62="416">>theend.lvl
echo.61="720">>theend.lvl
echo.60="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.52="432">>theend.lvl
echo.51="720">>theend.lvl
echo.50="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.42="384">>theend.lvl
echo.41="736">>theend.lvl
echo.40="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.32="400">>theend.lvl
echo.31="736">>theend.lvl
echo.30="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.22="416">>theend.lvl
echo.21="736">>theend.lvl
echo.20="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.12="432">>theend.lvl
echo.11="736">>theend.lvl
echo.10="obj_LE_tile_marioworld4_Colocado">>theend.lvl
echo.02="432">>theend.lvl
echo.01="1216">>theend.lvl
echo.00="obj_LE_tile_marioworld4_Colocado">>theend.lvl



echo.%msg13%
del temp2.log >nul
md %mundoname%
move "%~dp0mundo\*" "%~dp0%mundoname%" >nul
move "%~dp0%mundoname%.wrl" "%~dp0%mundoname%" >nul
move "%~dp0theend.lvl" "%~dp0%mundoname%" >nul
xcopy /i /s /-y "%~dp0%mundoname%" "%AppData%\Super_Mario_4_Jugadores\Mundos\%mundoname%"
rd /s /q "%mundoname%"
rd /s /q mundo
cls
echo.&echo.%msg01%
echo.          
echo.%msg02%
echo.%msg12%
echo.%msg14%：%mundoname%！
echo.%msg15%
echo.%msg16%
pause>nul
endlocal
exit

:errormax

cls
echo.&echo.%msg01%
echo.          
echo.%msg02%
echo.&echo.%errormax1%
echo.%errormax2%
echo.%errormax3%
echo.%errormax4%
echo.&echo.%errormax5%
pause>nul
cls
md cfg
echo.11100>cfg\maxnumber.cfg
goto start1